import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Alert } from 'react-native';
import type { TrialBalanceRow } from '@/api/trialBalance';
import type { JournalEntry } from '@/api/journalEntries';
import type { PurchaseOrder, POItem } from '@/api/purchaseOrders';
import type { SalesOrder, SOItem } from '@/api/salesOrders';
import type { StockBalance, StockLedgerEntry } from '@/api/inventory';
import type { Bookmark, BookmarkType } from '@/utils/bookmarks';
import { formatCurrency, formatDate } from '@/utils/currency';

// ─── shared HTML helpers ───────────────────────────────────────────────────

const BASE_CSS = `
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: -apple-system, 'Helvetica Neue', Arial, sans-serif;
    font-size: 11px;
    color: #0a0a0a;
    background: #fff;
    padding: 32px 36px;
  }
  .report-header { margin-bottom: 20px; }
  .report-title { font-size: 18px; font-weight: 800; letter-spacing: -0.3px; }
  .report-meta { font-size: 11px; color: #666; margin-top: 4px; }
  .summary-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 12px;
    margin: 16px 0;
  }
  .summary-block {
    border: 1px solid #e8e8e8;
    border-radius: 6px;
    padding: 12px 14px;
  }
  .summary-block .value { font-size: 15px; font-weight: 700; }
  .summary-block .label { font-size: 10px; color: #888; margin-top: 3px; }
  .net-row {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 10px 14px;
    border: 1px solid #0a0a0a;
    border-radius: 6px;
    margin: 8px 0 20px;
  }
  .net-label { font-size: 12px; font-weight: 700; }
  .net-value { font-size: 15px; font-weight: 800; }
  .section-label {
    font-size: 10px;
    font-weight: 700;
    letter-spacing: 0.8px;
    color: #888;
    text-transform: uppercase;
    margin: 16px 0 6px;
  }
  table {
    width: 100%;
    border-collapse: collapse;
    border: 1px solid #e8e8e8;
    border-radius: 6px;
    overflow: hidden;
    margin-bottom: 12px;
  }
  thead tr { background: #f5f5f5; }
  th {
    text-align: left;
    padding: 7px 10px;
    font-size: 10px;
    font-weight: 700;
    color: #666;
    border-bottom: 1px solid #e8e8e8;
  }
  th.right { text-align: right; }
  td { padding: 6px 10px; font-size: 11px; border-bottom: 1px solid #f0f0f0; }
  td.right { text-align: right; font-variant-numeric: tabular-nums; }
  td.muted { color: #aaa; }
  tr.group td { font-weight: 700; background: #fafafa; }
  tr.total td {
    font-weight: 700;
    font-size: 12px;
    background: #f5f5f5;
    border-top: 1px solid #e8e8e8;
    border-bottom: none;
  }
  .warning {
    border: 1px solid #e8e8e8;
    border-radius: 6px;
    background: #fafafa;
    padding: 8px 12px;
    font-size: 11px;
    color: #666;
    margin: 8px 0;
  }
  .footer {
    margin-top: 32px;
    padding-top: 12px;
    border-top: 1px solid #e8e8e8;
    font-size: 10px;
    color: #aaa;
    text-align: right;
  }
`;

function wrapHtml(title: string, body: string): string {
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${title}</title>
  <style>${BASE_CSS}</style>
</head>
<body>
  ${body}
  <div class="footer">Generated by Poultry ERP Mobile · ${new Date().toLocaleString()}</div>
</body>
</html>`;
}

async function printAndShare(html: string, filename: string): Promise<void> {
  try {
    const canShare = await Sharing.isAvailableAsync();
    if (canShare) {
      const { uri } = await Print.printToFileAsync({ html, base64: false });
      await Sharing.shareAsync(uri, {
        mimeType: 'application/pdf',
        dialogTitle: filename,
        UTI: 'com.adobe.pdf',
      });
    } else {
      // Fall back to the print dialog on platforms where sharing is unavailable
      await Print.printAsync({ html });
    }
  } catch (e: any) {
    Alert.alert('Export failed', e?.message ?? String(e));
  }
}

// ─── Trial Balance PDF ──────────────────────────────────────────────────────

export async function exportTrialBalancePDF(params: {
  rows: TrialBalanceRow[];
  companyName: string;
  asOf: string;
  totalDebit: number;
  totalCredit: number;
}): Promise<void> {
  const { rows, companyName, asOf, totalDebit, totalCredit } = params;
  const isBalanced = Math.abs(totalDebit - totalCredit) < 0.01;

  const tableRows = rows.map((r) => {
    const indent = (r.level ?? 0) * 16;
    const name = r.account_code ? `${r.account_code} — ${r.account_name ?? ''}` : (r.account_name ?? '');
    const dr = r.debit > 0 ? formatCurrency(r.debit) : '';
    const cr = r.credit > 0 ? formatCurrency(r.credit) : '';
    return `<tr${r.is_group ? ' class="group"' : ''}>
      <td style="padding-left:${10 + indent}px">${name}</td>
      <td class="right${!r.debit ? ' muted' : ''}">${dr || '—'}</td>
      <td class="right${!r.credit ? ' muted' : ''}">${cr || '—'}</td>
    </tr>`;
  }).join('');

  const body = `
    <div class="report-header">
      <div class="report-title">Trial Balance</div>
      <div class="report-meta">Company: ${companyName} &nbsp;·&nbsp; As of: ${asOf}</div>
    </div>

    ${!isBalanced ? `<div class="warning">⚠ Out of balance by ${formatCurrency(Math.abs(totalDebit - totalCredit))}</div>` : ''}

    <table>
      <thead>
        <tr>
          <th>Account</th>
          <th class="right">Debit</th>
          <th class="right">Credit</th>
        </tr>
      </thead>
      <tbody>
        ${tableRows}
        <tr class="total">
          <td>TOTAL</td>
          <td class="right">${formatCurrency(totalDebit)}</td>
          <td class="right">${formatCurrency(totalCredit)}</td>
        </tr>
      </tbody>
    </table>
    ${isBalanced ? '<div class="warning" style="background:#f0faf0">✓ Balanced</div>' : ''}
  `;

  await printAndShare(wrapHtml('Trial Balance', body), 'trial-balance.pdf');
}

// ─── P&L PDF ────────────────────────────────────────────────────────────────

interface PLData {
  revenues: TrialBalanceRow[];
  expenses: TrialBalanceRow[];
  totalRevenue: number;
  totalExpense: number;
  netIncome: number;
}

export async function exportPLPDF(params: {
  pl: PLData;
  companyName: string;
  asOf: string;
}): Promise<void> {
  const { pl, companyName, asOf } = params;

  const revenueRows = pl.revenues.map((r) => `
    <tr>
      <td>${r.account_code ? `${r.account_code} — ` : ''}${r.account_name ?? ''}</td>
      <td class="right">${formatCurrency(Math.abs(r.balance ?? r.credit - r.debit))}</td>
    </tr>`).join('');

  const expenseRows = pl.expenses.map((r) => `
    <tr>
      <td>${r.account_code ? `${r.account_code} — ` : ''}${r.account_name ?? ''}</td>
      <td class="right">${formatCurrency(Math.abs(r.balance ?? r.debit - r.credit))}</td>
    </tr>`).join('');

  const body = `
    <div class="report-header">
      <div class="report-title">Profit &amp; Loss Statement</div>
      <div class="report-meta">Company: ${companyName} &nbsp;·&nbsp; As of: ${asOf}</div>
    </div>

    <div class="summary-grid">
      <div class="summary-block">
        <div class="value">${formatCurrency(pl.totalRevenue)}</div>
        <div class="label">Total Revenue</div>
      </div>
      <div class="summary-block">
        <div class="value">${formatCurrency(pl.totalExpense)}</div>
        <div class="label">Total Expenses</div>
      </div>
    </div>

    <div class="net-row">
      <span class="net-label">Net Income</span>
      <span class="net-value">${formatCurrency(pl.netIncome)}</span>
    </div>

    <div class="section-label">Revenue</div>
    <table>
      <thead><tr><th>Account</th><th class="right">Amount</th></tr></thead>
      <tbody>
        ${revenueRows || '<tr><td colspan="2" class="muted">No revenue accounts</td></tr>'}
        <tr class="total">
          <td>Total Revenue</td>
          <td class="right">${formatCurrency(pl.totalRevenue)}</td>
        </tr>
      </tbody>
    </table>

    <div class="section-label">Expenses</div>
    <table>
      <thead><tr><th>Account</th><th class="right">Amount</th></tr></thead>
      <tbody>
        ${expenseRows || '<tr><td colspan="2" class="muted">No expense accounts</td></tr>'}
        <tr class="total">
          <td>Total Expenses</td>
          <td class="right">${formatCurrency(pl.totalExpense)}</td>
        </tr>
      </tbody>
    </table>
  `;

  await printAndShare(wrapHtml('Profit & Loss', body), 'profit-and-loss.pdf');
}

// ─── Balance Sheet PDF ───────────────────────────────────────────────────────

interface BSData {
  assets: TrialBalanceRow[];
  liabilities: TrialBalanceRow[];
  equity: TrialBalanceRow[];
  totalAssets: number;
  totalLiabilities: number;
  totalEquity: number;
}

function accountTableHtml(rows: TrialBalanceRow[], totalLabel: string, total: number): string {
  const dataRows = rows.map((r) => `
    <tr>
      <td>${r.account_code ? `${r.account_code} — ` : ''}${r.account_name ?? ''}</td>
      <td class="right">${formatCurrency(Math.abs(r.balance ?? Math.abs(r.debit - r.credit)))}</td>
    </tr>`).join('');

  return `
    <table>
      <thead><tr><th>Account</th><th class="right">Amount</th></tr></thead>
      <tbody>
        ${dataRows || '<tr><td colspan="2" class="muted">No accounts found</td></tr>'}
        <tr class="total">
          <td>${totalLabel}</td>
          <td class="right">${formatCurrency(total)}</td>
        </tr>
      </tbody>
    </table>`;
}

export async function exportBSPDF(params: {
  bs: BSData;
  companyName: string;
  asOf: string;
}): Promise<void> {
  const { bs, companyName, asOf } = params;
  const le = bs.totalLiabilities + bs.totalEquity;
  const isBalanced = Math.abs(bs.totalAssets - le) < 0.01;

  const body = `
    <div class="report-header">
      <div class="report-title">Balance Sheet</div>
      <div class="report-meta">Company: ${companyName} &nbsp;·&nbsp; As of: ${asOf}</div>
    </div>

    <div class="summary-grid">
      <div class="summary-block">
        <div class="value">${formatCurrency(bs.totalAssets)}</div>
        <div class="label">Total Assets</div>
      </div>
      <div class="summary-block">
        <div class="value">${formatCurrency(le)}</div>
        <div class="label">Liabilities + Equity</div>
      </div>
    </div>

    ${!isBalanced ? `<div class="warning">⚠ Out of balance by ${formatCurrency(Math.abs(bs.totalAssets - le))}</div>` : ''}

    <div class="section-label">Assets</div>
    ${accountTableHtml(bs.assets, 'Total Assets', bs.totalAssets)}

    <div class="section-label">Liabilities</div>
    ${accountTableHtml(bs.liabilities, 'Total Liabilities', bs.totalLiabilities)}

    <div class="section-label">Equity</div>
    ${accountTableHtml(bs.equity, 'Total Equity', bs.totalEquity)}

    <div class="net-row">
      <span class="net-label">Total L + E</span>
      <span class="net-value">${formatCurrency(le)}</span>
    </div>
  `;

  await printAndShare(wrapHtml('Balance Sheet', body), 'balance-sheet.pdf');
}

// ─── Stock Balances PDF ──────────────────────────────────────────────────────

export interface StockBalanceRow {
  item_name: string;
  item_code?: string;
  warehouse_name?: string;
  qty: number;
  unit?: string;
}

export async function exportStockBalancePDF(params: {
  rows: StockBalanceRow[];
  companyName: string;
  filter?: string;
}): Promise<void> {
  const { rows, companyName, filter } = params;

  const totalQty = rows.reduce((s, r) => s + (r.qty ?? 0), 0);

  const tableRows = rows
    .map((r) => {
      const name = r.item_code ? `${r.item_code} — ${r.item_name}` : r.item_name;
      const qtyClass = r.qty <= 0 ? 'muted' : '';
      return `<tr>
        <td>${name}</td>
        <td>${r.warehouse_name ?? '—'}</td>
        <td class="right ${qtyClass}">${r.qty ?? 0}</td>
        <td>${r.unit ?? ''}</td>
      </tr>`;
    })
    .join('');

  const metaParts = [companyName];
  if (filter && filter !== 'All') metaParts.push(`Filter: ${filter}`);

  const body = `
    <div class="report-header">
      <div class="report-title">Stock Balances</div>
      <div class="report-meta">${metaParts.join(' &nbsp;·&nbsp; ')} &nbsp;·&nbsp; ${new Date().toLocaleDateString()}</div>
    </div>

    <div class="summary-grid">
      <div class="summary-block">
        <div class="value">${rows.length}</div>
        <div class="label">Items</div>
      </div>
      <div class="summary-block">
        <div class="value">${totalQty.toLocaleString()}</div>
        <div class="label">Total Quantity</div>
      </div>
    </div>

    <table>
      <thead>
        <tr>
          <th>Item</th>
          <th>Warehouse</th>
          <th class="right">Qty</th>
          <th>Unit</th>
        </tr>
      </thead>
      <tbody>
        ${tableRows || '<tr><td colspan="4" class="muted">No stock data</td></tr>'}
        <tr class="total">
          <td colspan="2">TOTAL</td>
          <td class="right">${totalQty.toLocaleString()}</td>
          <td></td>
        </tr>
      </tbody>
    </table>
  `;

  await printAndShare(wrapHtml('Stock Balances', body), 'stock-balances.pdf');
}

// ─── Combined Financial Reports PDF ─────────────────────────────────────────

function classifyRow(
  row: TrialBalanceRow,
): 'revenue' | 'expense' | 'asset' | 'liability' | 'equity' | null {
  const type = (row.account_type ?? row.account_name ?? '').toLowerCase();
  if (type.includes('revenue') || type.includes('income') || type.includes('sales')) return 'revenue';
  if (type.includes('expense') || type.includes('cost') || type.includes('cogs')) return 'expense';
  if (
    type.includes('asset') ||
    type.includes('receivable') ||
    type.includes('inventory') ||
    type.includes('cash')
  )
    return 'asset';
  if (type.includes('liability') || type.includes('payable') || type.includes('loan'))
    return 'liability';
  if (type.includes('equity') || type.includes('capital') || type.includes('retained'))
    return 'equity';
  return null;
}

const COMBINED_EXTRA_CSS = `
  .page-break { page-break-before: always; margin: 48px 0 0; border-top: 2px solid #0a0a0a; padding-top: 32px; }
  .report-bundle-cover {
    display: flex;
    flex-direction: column;
    justify-content: center;
    min-height: 200px;
    border: 1px solid #0a0a0a;
    border-radius: 8px;
    padding: 32px 36px;
    margin-bottom: 32px;
  }
  .bundle-title { font-size: 22px; font-weight: 800; letter-spacing: -0.5px; margin-bottom: 8px; }
  .bundle-meta { font-size: 12px; color: #555; line-height: 1.8; }
  .toc { margin-top: 20px; }
  .toc-item {
    display: flex;
    align-items: baseline;
    gap: 8px;
    padding: 6px 0;
    border-bottom: 1px solid #f0f0f0;
    font-size: 12px;
  }
  .toc-num { font-weight: 700; color: #888; width: 20px; }
  .toc-label { flex: 1; }
`;

export async function exportCombinedReportPDF(params: {
  rows: TrialBalanceRow[];
  companyName: string;
  asOf: string;
  totalDebit: number;
  totalCredit: number;
}): Promise<void> {
  const { rows, companyName, asOf, totalDebit, totalCredit } = params;

  // Classify rows
  const revenues = rows.filter((r) => classifyRow(r) === 'revenue');
  const expenses = rows.filter((r) => classifyRow(r) === 'expense');
  const assets = rows.filter((r) => classifyRow(r) === 'asset');
  const liabilities = rows.filter((r) => classifyRow(r) === 'liability');
  const equity = rows.filter((r) => classifyRow(r) === 'equity');

  const totalRevenue = revenues.reduce((s, r) => s + Math.abs(r.balance ?? r.credit - r.debit), 0);
  const totalExpense = expenses.reduce((s, r) => s + Math.abs(r.balance ?? r.debit - r.credit), 0);
  const netIncome = totalRevenue - totalExpense;
  const totalAssets = assets.reduce((s, r) => s + Math.abs(r.balance ?? r.debit - r.credit), 0);
  const totalLiabilities = liabilities.reduce(
    (s, r) => s + Math.abs(r.balance ?? r.credit - r.debit),
    0,
  );
  const totalEquity = equity.reduce((s, r) => s + Math.abs(r.balance ?? r.credit - r.debit), 0);
  const le = totalLiabilities + totalEquity;
  const isTBBalanced = Math.abs(totalDebit - totalCredit) < 0.01;
  const isBSBalanced = Math.abs(totalAssets - le) < 0.01;

  // TB rows HTML
  const tbRowsHtml = rows
    .map((r) => {
      const indent = (r.level ?? 0) * 16;
      const name = r.account_code
        ? `${r.account_code} — ${r.account_name ?? ''}`
        : (r.account_name ?? '');
      const dr = r.debit > 0 ? formatCurrency(r.debit) : '';
      const cr = r.credit > 0 ? formatCurrency(r.credit) : '';
      return `<tr${r.is_group ? ' class="group"' : ''}>
        <td style="padding-left:${10 + indent}px">${name}</td>
        <td class="right${!r.debit ? ' muted' : ''}">${dr || '—'}</td>
        <td class="right${!r.credit ? ' muted' : ''}">${cr || '—'}</td>
      </tr>`;
    })
    .join('');

  // Helper for single-amount account rows
  const accountRows = (accs: TrialBalanceRow[], totalLabel: string, total: number) => {
    const rows2 = accs
      .map(
        (r) => `<tr>
        <td>${r.account_code ? `${r.account_code} — ` : ''}${r.account_name ?? ''}</td>
        <td class="right">${formatCurrency(Math.abs(r.balance ?? Math.abs(r.debit - r.credit)))}</td>
      </tr>`,
      )
      .join('');
    return `<table>
      <thead><tr><th>Account</th><th class="right">Amount</th></tr></thead>
      <tbody>
        ${rows2 || '<tr><td colspan="2" class="muted">No accounts</td></tr>'}
        <tr class="total"><td>${totalLabel}</td><td class="right">${formatCurrency(total)}</td></tr>
      </tbody>
    </table>`;
  };

  const meta = `Company: ${companyName} &nbsp;·&nbsp; As of: ${asOf}`;

  const body = `
    <!-- Cover -->
    <div class="report-bundle-cover">
      <div class="bundle-title">Financial Reports Bundle</div>
      <div class="bundle-meta">
        <div>Company: <strong>${companyName}</strong></div>
        <div>As of: <strong>${asOf}</strong></div>
        <div>Generated: ${new Date().toLocaleDateString()}</div>
      </div>
      <div class="toc">
        <div class="toc-item"><span class="toc-num">1</span><span class="toc-label">Trial Balance</span></div>
        <div class="toc-item"><span class="toc-num">2</span><span class="toc-label">Profit &amp; Loss Statement</span></div>
        <div class="toc-item"><span class="toc-num">3</span><span class="toc-label">Balance Sheet</span></div>
      </div>
    </div>

    <!-- 1. Trial Balance -->
    <div class="report-header">
      <div class="report-title">1 &nbsp; Trial Balance</div>
      <div class="report-meta">${meta}</div>
    </div>
    ${!isTBBalanced ? `<div class="warning">Out of balance by ${formatCurrency(Math.abs(totalDebit - totalCredit))}</div>` : ''}
    <table>
      <thead><tr><th>Account</th><th class="right">Debit</th><th class="right">Credit</th></tr></thead>
      <tbody>
        ${tbRowsHtml}
        <tr class="total">
          <td>TOTAL</td>
          <td class="right">${formatCurrency(totalDebit)}</td>
          <td class="right">${formatCurrency(totalCredit)}</td>
        </tr>
      </tbody>
    </table>
    ${isTBBalanced ? '<div class="warning" style="background:#f0faf0">✓ Balanced</div>' : ''}

    <!-- 2. Profit & Loss -->
    <div class="page-break">
      <div class="report-title">2 &nbsp; Profit &amp; Loss Statement</div>
      <div class="report-meta">${meta}</div>
    </div>
    <div class="summary-grid" style="margin-top:16px">
      <div class="summary-block">
        <div class="value">${formatCurrency(totalRevenue)}</div>
        <div class="label">Total Revenue</div>
      </div>
      <div class="summary-block">
        <div class="value">${formatCurrency(totalExpense)}</div>
        <div class="label">Total Expenses</div>
      </div>
    </div>
    <div class="net-row">
      <span class="net-label">Net Income</span>
      <span class="net-value">${formatCurrency(netIncome)}</span>
    </div>
    <div class="section-label">Revenue</div>
    ${accountRows(revenues, 'Total Revenue', totalRevenue)}
    <div class="section-label">Expenses</div>
    ${accountRows(expenses, 'Total Expenses', totalExpense)}

    <!-- 3. Balance Sheet -->
    <div class="page-break">
      <div class="report-title">3 &nbsp; Balance Sheet</div>
      <div class="report-meta">${meta}</div>
    </div>
    <div class="summary-grid" style="margin-top:16px">
      <div class="summary-block">
        <div class="value">${formatCurrency(totalAssets)}</div>
        <div class="label">Total Assets</div>
      </div>
      <div class="summary-block">
        <div class="value">${formatCurrency(le)}</div>
        <div class="label">Liabilities + Equity</div>
      </div>
    </div>
    ${!isBSBalanced ? `<div class="warning">Out of balance by ${formatCurrency(Math.abs(totalAssets - le))}</div>` : ''}
    <div class="section-label">Assets</div>
    ${accountRows(assets, 'Total Assets', totalAssets)}
    <div class="section-label">Liabilities</div>
    ${accountRows(liabilities, 'Total Liabilities', totalLiabilities)}
    <div class="section-label">Equity</div>
    ${accountRows(equity, 'Total Equity', totalEquity)}
    <div class="net-row">
      <span class="net-label">Total L + E</span>
      <span class="net-value">${formatCurrency(le)}</span>
    </div>
  `;

  // Inject extra CSS into the combined wrapper
  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Financial Reports Bundle</title>
  <style>${BASE_CSS}${COMBINED_EXTRA_CSS}</style>
</head>
<body>
  ${body}
  <div class="footer">Generated by Poultry ERP Mobile · ${new Date().toLocaleString()}</div>
</body>
</html>`;

  await printAndShare(html, 'financial-reports-bundle.pdf');
}

// ─── Journal Entries PDF ─────────────────────────────────────────────────────

export async function exportJournalEntriesPDF(params: {
  entries: JournalEntry[];
  companyName: string;
  type: string;
  from?: string;
  to?: string;
}): Promise<void> {
  const { entries, companyName, type, from, to } = params;

  const entryRows = entries.map((e) => {
    const lineRows = (e.lines ?? []).map((l) => `
      <tr>
        <td style="padding-left:24px;color:#555">${l.account ?? ''}</td>
        <td class="right">${l.debit ? formatCurrency(l.debit) : ''}</td>
        <td class="right">${l.credit ? formatCurrency(l.credit) : ''}</td>
      </tr>`).join('');

    return `
      <tr class="group">
        <td>
          <span style="font-weight:700">${e.voucher_type ?? ''} ${e.voucher_no ?? ''}</span>
          <span style="font-weight:400;color:#888;margin-left:8px">${e.dt ?? ''}</span>
        </td>
        <td class="right">${e.total_debit ? formatCurrency(e.total_debit) : ''}</td>
        <td class="right">${e.total_credit ? formatCurrency(e.total_credit) : ''}</td>
      </tr>
      ${e.narration ? `<tr><td colspan="3" style="color:#777;padding-left:12px;font-style:italic">${e.narration}</td></tr>` : ''}
      ${lineRows}`;
  }).join('');

  const metaParts = [companyName];
  if (type !== 'All') metaParts.push(`Type: ${type}`);
  if (from) metaParts.push(`From: ${from}`);
  if (to) metaParts.push(`To: ${to}`);

  const body = `
    <div class="report-header">
      <div class="report-title">Journal Entries</div>
      <div class="report-meta">${metaParts.join(' &nbsp;·&nbsp; ')}</div>
    </div>

    <div class="summary-grid">
      <div class="summary-block">
        <div class="value">${entries.length}</div>
        <div class="label">Total Vouchers</div>
      </div>
      <div class="summary-block">
        <div class="value">${formatCurrency(entries.reduce((s, e) => s + (e.total_debit ?? 0), 0))}</div>
        <div class="label">Total Amount</div>
      </div>
    </div>

    <table>
      <thead>
        <tr>
          <th>Voucher / Account</th>
          <th class="right">Debit</th>
          <th class="right">Credit</th>
        </tr>
      </thead>
      <tbody>
        ${entryRows || '<tr><td colspan="3" class="muted">No entries</td></tr>'}
      </tbody>
    </table>
  `;

  await printAndShare(wrapHtml('Journal Entries', body), 'journal-entries.pdf');
}

// ─── Purchase Order Detail PDF ───────────────────────────────────────────────

export async function exportPODetailPDF(po: PurchaseOrder): Promise<void> {
  const items: POItem[] = po.items ?? [];
  const totalOrdered = items.reduce((s, i) => s + (i.qty_ordered ?? 0), 0);
  const totalReceived = items.reduce((s, i) => s + (i.qty_received ?? 0), 0);
  const progressPct = totalOrdered > 0 ? Math.round((totalReceived / totalOrdered) * 100) : 0;

  const itemRows = items
    .map(
      (i) => `<tr>
        <td>${i.item_name}</td>
        <td class="right">${i.qty_ordered.toLocaleString()}</td>
        <td class="right">${(i.qty_received ?? 0).toLocaleString()}</td>
        <td class="right">${(i.qty_ordered - (i.qty_received ?? 0)).toLocaleString()}</td>
        <td>${i.unit ?? ''}</td>
        <td class="right">${i.rate != null ? formatCurrency(i.rate) : ''}</td>
        <td class="right">${i.amount != null ? formatCurrency(i.amount) : ''}</td>
      </tr>`,
    )
    .join('');

  const body = `
    <div class="report-header">
      <div class="report-title">${po.po_number ?? `PO-${po.id}`}</div>
      <div class="report-meta">Purchase Order &nbsp;·&nbsp; ${po.vendor ?? 'Unknown Vendor'} &nbsp;·&nbsp; ${new Date().toLocaleDateString()}</div>
    </div>

    <div class="summary-grid">
      <div class="summary-block">
        <div class="value">${po.status ?? '—'}</div>
        <div class="label">Status</div>
      </div>
      <div class="summary-block">
        <div class="value">${po.total != null ? formatCurrency(po.total) : '—'}</div>
        <div class="label">Total Amount</div>
      </div>
      ${po.dt ? `<div class="summary-block">
        <div class="value">${formatDate(po.dt)}</div>
        <div class="label">Order Date</div>
      </div>` : ''}
      ${po.delivery_date ? `<div class="summary-block">
        <div class="value">${formatDate(po.delivery_date)}</div>
        <div class="label">Delivery Date</div>
      </div>` : ''}
    </div>

    ${items.length > 0 ? `<div class="net-row">
      <span class="net-label">Receipt Progress</span>
      <span class="net-value">${progressPct}% &nbsp; (${totalReceived.toLocaleString()} / ${totalOrdered.toLocaleString()} units)</span>
    </div>` : ''}

    ${po.notes ? `<div class="warning">Notes: ${po.notes}</div>` : ''}

    <div class="section-label">Line Items (${items.length})</div>
    <table>
      <thead>
        <tr>
          <th>Item</th>
          <th class="right">Ordered</th>
          <th class="right">Received</th>
          <th class="right">Pending</th>
          <th>Unit</th>
          <th class="right">Rate</th>
          <th class="right">Amount</th>
        </tr>
      </thead>
      <tbody>
        ${itemRows || '<tr><td colspan="7" class="muted">No line items</td></tr>'}
        ${items.length > 0 ? `<tr class="total">
          <td>TOTAL</td>
          <td class="right">${totalOrdered.toLocaleString()}</td>
          <td class="right">${totalReceived.toLocaleString()}</td>
          <td class="right">${(totalOrdered - totalReceived).toLocaleString()}</td>
          <td colspan="2"></td>
          <td class="right">${po.total != null ? formatCurrency(po.total) : ''}</td>
        </tr>` : ''}
      </tbody>
    </table>
  `;

  const filename = (po.po_number ?? `PO-${po.id}`).replace(/[^a-zA-Z0-9-]/g, '-') + '.pdf';
  await printAndShare(wrapHtml(`Purchase Order — ${po.po_number ?? po.id}`, body), filename);
}

// ─── Sales Order Detail PDF ──────────────────────────────────────────────────

export async function exportSODetailPDF(so: SalesOrder): Promise<void> {
  const items: SOItem[] = so.items ?? [];
  const totalQty = items.reduce((s, i) => s + (i.qty ?? 0), 0);

  const itemRows = items
    .map(
      (i) => `<tr>
        <td>${i.item_name}</td>
        <td class="right">${(i.qty ?? 0).toLocaleString()}</td>
        <td>${i.unit ?? ''}</td>
        <td class="right">${i.rate != null ? formatCurrency(i.rate) : ''}</td>
        <td class="right">${i.amount != null ? formatCurrency(i.amount) : ''}</td>
      </tr>`,
    )
    .join('');

  const body = `
    <div class="report-header">
      <div class="report-title">${so.so_number ?? `SO-${so.id}`}</div>
      <div class="report-meta">Sales Order &nbsp;·&nbsp; ${so.customer ?? 'Unknown Customer'} &nbsp;·&nbsp; ${new Date().toLocaleDateString()}</div>
    </div>

    <div class="summary-grid">
      <div class="summary-block">
        <div class="value">${so.status ?? '—'}</div>
        <div class="label">Status</div>
      </div>
      <div class="summary-block">
        <div class="value">${so.total != null ? formatCurrency(so.total) : '—'}</div>
        <div class="label">Total Amount</div>
      </div>
      ${so.dt ? `<div class="summary-block">
        <div class="value">${formatDate(so.dt)}</div>
        <div class="label">Order Date</div>
      </div>` : ''}
      ${so.delivery_date ? `<div class="summary-block">
        <div class="value">${formatDate(so.delivery_date)}</div>
        <div class="label">Delivery Date</div>
      </div>` : ''}
    </div>

    ${so.notes ? `<div class="warning">Notes: ${so.notes}</div>` : ''}

    <div class="section-label">Line Items (${items.length})</div>
    <table>
      <thead>
        <tr>
          <th>Item</th>
          <th class="right">Qty</th>
          <th>Unit</th>
          <th class="right">Rate</th>
          <th class="right">Amount</th>
        </tr>
      </thead>
      <tbody>
        ${itemRows || '<tr><td colspan="5" class="muted">No line items</td></tr>'}
        ${items.length > 0 ? `<tr class="total">
          <td>TOTAL</td>
          <td class="right">${totalQty.toLocaleString()}</td>
          <td colspan="2"></td>
          <td class="right">${so.total != null ? formatCurrency(so.total) : ''}</td>
        </tr>` : ''}
      </tbody>
    </table>
  `;

  const filename = (so.so_number ?? `SO-${so.id}`).replace(/[^a-zA-Z0-9-]/g, '-') + '.pdf';
  await printAndShare(wrapHtml(`Sales Order — ${so.so_number ?? so.id}`, body), filename);
}

// ─── Bookmarks PDF ───────────────────────────────────────────────────────────

const BOOKMARK_TYPE_LABELS: Record<BookmarkType, string> = {
  po: 'Purchase Orders',
  so: 'Sales Orders',
  partner: 'Partners',
  material: 'Materials',
};

export async function exportBookmarksPDF(bookmarks: Bookmark[]): Promise<void> {
  const byType: Record<BookmarkType, Bookmark[]> = { po: [], so: [], partner: [], material: [] };
  for (const b of bookmarks) {
    byType[b.type].push(b);
  }

  const typeOrder: BookmarkType[] = ['po', 'so', 'partner', 'material'];

  let sections = '';
  for (const type of typeOrder) {
    const list = byType[type];
    if (list.length === 0) continue;
    const label = BOOKMARK_TYPE_LABELS[type];
    const rows = list
      .map(
        (b) => `<tr>
          <td>${b.title}</td>
          <td>${b.subtitle ?? ''}</td>
          <td class="right">${b.meta ?? ''}</td>
          <td class="muted">${new Date(b.addedAt).toLocaleDateString()}</td>
        </tr>`,
      )
      .join('');
    sections += `
      <div class="section-label">${label} (${list.length})</div>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Details</th>
            <th class="right">Amount / Info</th>
            <th>Saved</th>
          </tr>
        </thead>
        <tbody>${rows}</tbody>
      </table>
    `;
  }

  const body = `
    <div class="report-header">
      <div class="report-title">Bookmarks</div>
      <div class="report-meta">${bookmarks.length} saved items &nbsp;·&nbsp; ${new Date().toLocaleDateString()}</div>
    </div>

    <div class="summary-grid">
      ${typeOrder
        .filter((t) => byType[t].length > 0)
        .map(
          (t) => `<div class="summary-block">
            <div class="value">${byType[t].length}</div>
            <div class="label">${BOOKMARK_TYPE_LABELS[t]}</div>
          </div>`,
        )
        .join('')}
    </div>

    ${sections || '<div class="warning">No bookmarks saved.</div>'}
  `;

  await printAndShare(wrapHtml('Bookmarks', body), 'bookmarks.pdf');
}

// ─── Partner Detail PDF ──────────────────────────────────────────────────────

export async function exportPartnerDetailPDF(params: {
  partnerName: string;
  roles: string[];
  pos: PurchaseOrder[];
  sos: SalesOrder[];
}): Promise<void> {
  const { partnerName, roles, pos, sos } = params;
  const poTotal = pos.reduce((s, p) => s + (p.total ?? 0), 0);
  const soTotal = sos.reduce((s, s2) => s + (s2.total ?? 0), 0);

  const poRows = pos
    .map(
      (p) => `<tr>
        <td>${p.po_number ?? `PO-${p.id}`}</td>
        <td>${p.dt ? formatDate(p.dt) : '—'}</td>
        <td>${p.status ?? '—'}</td>
        <td class="right">${p.total != null ? formatCurrency(p.total) : '—'}</td>
      </tr>`,
    )
    .join('');

  const soRows = sos
    .map(
      (s) => `<tr>
        <td>${s.so_number ?? `SO-${s.id}`}</td>
        <td>${s.dt ? formatDate(s.dt) : '—'}</td>
        <td>${s.status ?? '—'}</td>
        <td class="right">${s.total != null ? formatCurrency(s.total) : '—'}</td>
      </tr>`,
    )
    .join('');

  const summaryBlocks = [
    pos.length > 0
      ? `<div class="summary-block">
          <div class="value">${formatCurrency(poTotal)}</div>
          <div class="label">Total POs (${pos.length})</div>
        </div>`
      : '',
    sos.length > 0
      ? `<div class="summary-block">
          <div class="value">${formatCurrency(soTotal)}</div>
          <div class="label">Total SOs (${sos.length})</div>
        </div>`
      : '',
  ].join('');

  const poSection =
    pos.length > 0
      ? `<div class="section-label">Purchase Orders (${pos.length})</div>
         <table>
           <thead><tr><th>PO Number</th><th>Date</th><th>Status</th><th class="right">Amount</th></tr></thead>
           <tbody>
             ${poRows}
             <tr class="total"><td colspan="3">TOTAL</td><td class="right">${formatCurrency(poTotal)}</td></tr>
           </tbody>
         </table>`
      : '';

  const soSection =
    sos.length > 0
      ? `<div class="section-label">Sales Orders (${sos.length})</div>
         <table>
           <thead><tr><th>SO Number</th><th>Date</th><th>Status</th><th class="right">Amount</th></tr></thead>
           <tbody>
             ${soRows}
             <tr class="total"><td colspan="3">TOTAL</td><td class="right">${formatCurrency(soTotal)}</td></tr>
           </tbody>
         </table>`
      : '';

  const body = `
    <div class="report-header">
      <div class="report-title">${partnerName}</div>
      <div class="report-meta">${roles.join(' · ')} &nbsp;·&nbsp; ${new Date().toLocaleDateString()}</div>
    </div>

    <div class="summary-grid">${summaryBlocks}</div>

    ${poSection}
    ${soSection}
    ${!poSection && !soSection ? '<div class="warning">No order history found.</div>' : ''}
  `;

  const filename = partnerName.replace(/[^a-zA-Z0-9-]/g, '-') + '-partner.pdf';
  await printAndShare(wrapHtml(`Partner — ${partnerName}`, body), filename);
}

// ─── Material Detail PDF ─────────────────────────────────────────────────────

export async function exportMaterialDetailPDF(params: {
  materialName: string;
  materialCode?: string;
  materialType?: string;
  materialUnit?: string;
  materialCategory?: string;
  materialStatus?: string;
  stock: StockBalance[];
  ledger: StockLedgerEntry[];
}): Promise<void> {
  const {
    materialName,
    materialCode,
    materialType,
    materialUnit,
    materialCategory,
    materialStatus,
    stock,
    ledger,
  } = params;

  const totalQty = stock.reduce((s, b) => s + (Number(b.qty) || 0), 0);
  const totalIn = ledger.reduce((s, e) => s + (Number(e.qty_in) || 0), 0);
  const totalOut = ledger.reduce((s, e) => s + (Number(e.qty_out) || 0), 0);
  const unit = stock[0]?.unit ?? materialUnit ?? '';

  const stockRows = stock
    .map(
      (b) => `<tr>
        <td>${b.warehouse_name ?? '—'}</td>
        <td class="right">${Number(b.qty).toLocaleString()}</td>
        <td>${b.unit ?? unit}</td>
        ${b.qty <= 0 ? '<td class="muted">Out of Stock</td>' : b.qty < 100 ? '<td class="muted">Low Stock</td>' : '<td></td>'}
      </tr>`,
    )
    .join('');

  const ledgerRows = ledger
    .map(
      (e) => `<tr>
        <td>${e.dt ? formatDate(e.dt) : '—'}</td>
        <td>${e.voucher_type ?? '—'}</td>
        <td>${e.voucher_no ?? '—'}</td>
        <td>${e.warehouse_name ?? '—'}</td>
        <td class="right">${e.qty_in ? `+${Number(e.qty_in).toLocaleString()}` : ''}</td>
        <td class="right">${e.qty_out ? `-${Number(e.qty_out).toLocaleString()}` : ''}</td>
        <td class="right">${e.balance != null ? Number(e.balance).toLocaleString() : ''}</td>
      </tr>`,
    )
    .join('');

  const meta = [materialType, materialCategory, materialStatus].filter(Boolean).join(' · ');

  const body = `
    <div class="report-header">
      <div class="report-title">${materialName}${materialCode ? ` — ${materialCode}` : ''}</div>
      <div class="report-meta">${meta || 'Material'} &nbsp;·&nbsp; ${new Date().toLocaleDateString()}</div>
    </div>

    <div class="summary-grid">
      <div class="summary-block">
        <div class="value">${totalQty.toLocaleString()} ${unit}</div>
        <div class="label">Total Stock</div>
      </div>
      <div class="summary-block">
        <div class="value">${stock.length}</div>
        <div class="label">Warehouses</div>
      </div>
      <div class="summary-block">
        <div class="value">+${totalIn.toLocaleString()}</div>
        <div class="label">Total In</div>
      </div>
      <div class="summary-block">
        <div class="value">-${totalOut.toLocaleString()}</div>
        <div class="label">Total Out</div>
      </div>
    </div>

    ${stock.length > 0 ? `
    <div class="section-label">Stock by Warehouse (${stock.length})</div>
    <table>
      <thead><tr><th>Warehouse</th><th class="right">Qty</th><th>Unit</th><th>Status</th></tr></thead>
      <tbody>${stockRows}</tbody>
    </table>` : ''}

    ${ledger.length > 0 ? `
    <div class="section-label">Transactions (${ledger.length})</div>
    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>Type</th>
          <th>Voucher</th>
          <th>Warehouse</th>
          <th class="right">In</th>
          <th class="right">Out</th>
          <th class="right">Balance</th>
        </tr>
      </thead>
      <tbody>${ledgerRows}</tbody>
    </table>` : ''}
  `;

  const filename = materialName.replace(/[^a-zA-Z0-9-]/g, '-') + '-material.pdf';
  await printAndShare(wrapHtml(`Material — ${materialName}`, body), filename);
}

// ─── Vendor Detail PDF (AP bills) ────────────────────────────────────────────

export interface VendorBillRow {
  id: number;
  bill_number?: string;
  dt?: string;
  due_date?: string;
  amount?: number;
  paid?: number;
  outstanding?: number;
  status?: string;
}

export async function exportVendorDetailPDF(params: {
  vendorName: string;
  bills: VendorBillRow[];
  totalOutstanding: number;
  overdue: number;
}): Promise<void> {
  const { vendorName, bills, totalOutstanding, overdue } = params;
  const totalBilled = bills.reduce((s, b) => s + (b.amount ?? 0), 0);
  const totalPaid = bills.reduce((s, b) => s + (b.paid ?? 0), 0);

  const rows = bills
    .map(
      (b) => `<tr>
        <td>${b.bill_number ?? `Bill-${b.id}`}</td>
        <td>${b.dt ? formatDate(b.dt) : '—'}</td>
        <td>${b.due_date ? formatDate(b.due_date) : '—'}</td>
        <td>${b.status ?? '—'}</td>
        <td class="right">${b.amount != null ? formatCurrency(b.amount) : '—'}</td>
        <td class="right">${b.paid != null ? formatCurrency(b.paid) : '—'}</td>
        <td class="right">${b.outstanding != null ? formatCurrency(b.outstanding) : '—'}</td>
      </tr>`,
    )
    .join('');

  const body = `
    <div class="report-header">
      <div class="report-title">${vendorName}</div>
      <div class="report-meta">Vendor · Accounts Payable &nbsp;·&nbsp; ${new Date().toLocaleDateString()}</div>
    </div>

    <div class="summary-grid">
      <div class="summary-block">
        <div class="value">${formatCurrency(totalOutstanding)}</div>
        <div class="label">Outstanding</div>
      </div>
      <div class="summary-block">
        <div class="value">${formatCurrency(overdue)}</div>
        <div class="label">Overdue</div>
      </div>
      <div class="summary-block">
        <div class="value">${formatCurrency(totalBilled)}</div>
        <div class="label">Total Billed</div>
      </div>
      <div class="summary-block">
        <div class="value">${bills.length}</div>
        <div class="label">Bills</div>
      </div>
    </div>

    <div class="section-label">Bills (${bills.length})</div>
    <table>
      <thead>
        <tr>
          <th>Bill #</th>
          <th>Date</th>
          <th>Due Date</th>
          <th>Status</th>
          <th class="right">Amount</th>
          <th class="right">Paid</th>
          <th class="right">Outstanding</th>
        </tr>
      </thead>
      <tbody>
        ${rows || '<tr><td colspan="7" class="muted">No bills found</td></tr>'}
        ${bills.length > 0 ? `<tr class="total">
          <td colspan="4">TOTAL</td>
          <td class="right">${formatCurrency(totalBilled)}</td>
          <td class="right">${formatCurrency(totalPaid)}</td>
          <td class="right">${formatCurrency(totalOutstanding)}</td>
        </tr>` : ''}
      </tbody>
    </table>
  `;

  const filename = vendorName.replace(/[^a-zA-Z0-9-]/g, '-') + '-ap-bills.pdf';
  await printAndShare(wrapHtml(`Vendor AP — ${vendorName}`, body), filename);
}

// ─── Customer Detail PDF (AR invoices) ───────────────────────────────────────

export interface CustomerInvoiceRow {
  id: number;
  invoice_number?: string;
  dt?: string;
  due_date?: string;
  amount?: number;
  paid?: number;
  outstanding?: number;
  status?: string;
}

export async function exportCustomerDetailPDF(params: {
  customerName: string;
  invoices: CustomerInvoiceRow[];
  totalOutstanding: number;
  overdue: number;
}): Promise<void> {
  const { customerName, invoices, totalOutstanding, overdue } = params;
  const totalBilled = invoices.reduce((s, i) => s + (i.amount ?? 0), 0);
  const totalPaid = invoices.reduce((s, i) => s + (i.paid ?? 0), 0);

  const rows = invoices
    .map(
      (i) => `<tr>
        <td>${i.invoice_number ?? `Inv-${i.id}`}</td>
        <td>${i.dt ? formatDate(i.dt) : '—'}</td>
        <td>${i.due_date ? formatDate(i.due_date) : '—'}</td>
        <td>${i.status ?? '—'}</td>
        <td class="right">${i.amount != null ? formatCurrency(i.amount) : '—'}</td>
        <td class="right">${i.paid != null ? formatCurrency(i.paid) : '—'}</td>
        <td class="right">${i.outstanding != null ? formatCurrency(i.outstanding) : '—'}</td>
      </tr>`,
    )
    .join('');

  const body = `
    <div class="report-header">
      <div class="report-title">${customerName}</div>
      <div class="report-meta">Customer · Accounts Receivable &nbsp;·&nbsp; ${new Date().toLocaleDateString()}</div>
    </div>

    <div class="summary-grid">
      <div class="summary-block">
        <div class="value">${formatCurrency(totalOutstanding)}</div>
        <div class="label">Outstanding</div>
      </div>
      <div class="summary-block">
        <div class="value">${formatCurrency(overdue)}</div>
        <div class="label">Overdue</div>
      </div>
      <div class="summary-block">
        <div class="value">${formatCurrency(totalBilled)}</div>
        <div class="label">Total Billed</div>
      </div>
      <div class="summary-block">
        <div class="value">${invoices.length}</div>
        <div class="label">Invoices</div>
      </div>
    </div>

    <div class="section-label">Invoices (${invoices.length})</div>
    <table>
      <thead>
        <tr>
          <th>Invoice #</th>
          <th>Date</th>
          <th>Due Date</th>
          <th>Status</th>
          <th class="right">Amount</th>
          <th class="right">Paid</th>
          <th class="right">Outstanding</th>
        </tr>
      </thead>
      <tbody>
        ${rows || '<tr><td colspan="7" class="muted">No invoices found</td></tr>'}
        ${invoices.length > 0 ? `<tr class="total">
          <td colspan="4">TOTAL</td>
          <td class="right">${formatCurrency(totalBilled)}</td>
          <td class="right">${formatCurrency(totalPaid)}</td>
          <td class="right">${formatCurrency(totalOutstanding)}</td>
        </tr>` : ''}
      </tbody>
    </table>
  `;

  const filename = customerName.replace(/[^a-zA-Z0-9-]/g, '-') + '-ar-invoices.pdf';
  await printAndShare(wrapHtml(`Customer AR — ${customerName}`, body), filename);
}

// ─── Item Ledger PDF ──────────────────────────────────────────────────────────

export async function exportItemLedgerPDF(params: {
  itemName: string;
  itemCode?: string;
  companyName: string;
  dateRange?: { from?: string; to?: string };
  entries: StockLedgerEntry[];
  totalIn: number;
  totalOut: number;
  currentBalance: number | null;
}): Promise<void> {
  const { itemName, itemCode, companyName, dateRange, entries, totalIn, totalOut, currentBalance } = params;

  const dateInfo =
    dateRange?.from || dateRange?.to
      ? `${dateRange.from || 'Start'} → ${dateRange.to || 'Today'} &nbsp;·&nbsp; `
      : '';

  const rows = entries
    .map((e) => {
      const vtype = e.voucher_type ?? '';
      const qtyIn = e.qty_in ?? 0;
      const qtyOut = e.qty_out ?? 0;
      return `<tr>
        <td><span style="font-size:10px;font-weight:700;border:1px solid #e8e8e8;padding:1px 5px;border-radius:3px">${vtype || 'TXN'}</span></td>
        <td>${e.voucher_no ?? '—'}</td>
        <td>${e.dt ? formatDate(e.dt) : '—'}</td>
        <td>${e.warehouse_name ?? '—'}</td>
        <td class="right">${qtyIn > 0 ? `+${qtyIn.toLocaleString()}` : '—'}</td>
        <td class="right">${qtyOut > 0 ? `-${qtyOut.toLocaleString()}` : '—'}</td>
        <td class="right">${e.balance != null ? e.balance.toLocaleString() : '—'}</td>
        <td>${e.unit ?? '—'}</td>
      </tr>`;
    })
    .join('');

  const body = `
    <div class="report-header">
      <div class="report-title">${itemName}${itemCode ? ` <span style="font-size:12px;color:#888">(${itemCode})</span>` : ''}</div>
      <div class="report-meta">${dateInfo}Company: ${companyName} &nbsp;·&nbsp; ${new Date().toLocaleDateString()}</div>
    </div>

    <div class="summary-grid">
      <div class="summary-block">
        <div class="value">+${totalIn.toLocaleString()}</div>
        <div class="label">Total In</div>
      </div>
      <div class="summary-block">
        <div class="value">-${totalOut.toLocaleString()}</div>
        <div class="label">Total Out</div>
      </div>
      ${
        currentBalance != null
          ? `<div class="summary-block">
        <div class="value">${currentBalance.toLocaleString()}</div>
        <div class="label">Current Balance</div>
      </div>`
          : ''
      }
      <div class="summary-block">
        <div class="value">${entries.length}</div>
        <div class="label">Transactions</div>
      </div>
    </div>

    <div class="section-label">Movement Log (${entries.length} entries)</div>
    <table>
      <thead>
        <tr>
          <th>Type</th>
          <th>Voucher #</th>
          <th>Date</th>
          <th>Warehouse</th>
          <th class="right">In</th>
          <th class="right">Out</th>
          <th class="right">Balance</th>
          <th>Unit</th>
        </tr>
      </thead>
      <tbody>
        ${rows || '<tr><td colspan="8" class="muted">No transactions found</td></tr>'}
      </tbody>
    </table>
  `;

  const filename = itemName.replace(/[^a-zA-Z0-9-]/g, '-') + '-ledger.pdf';
  await printAndShare(wrapHtml(`Item Ledger — ${itemName}`, body), filename);
}

// ─── GRN (Goods Receipt) PDF ──────────────────────────────────────────────────

export async function exportGRNPDF(params: {
  companyName: string;
  orders: PurchaseOrder[];
}): Promise<void> {
  const { companyName, orders } = params;

  const totalReceived = orders.reduce((s, o) => s + (o.received ?? 0), 0);
  const totalOrdered = orders.reduce((s, o) => s + (o.total ?? 0), 0);
  const overallPct = totalOrdered > 0 ? Math.min((totalReceived / totalOrdered) * 100, 100) : 0;
  const completePOs = orders.filter((o) => {
    const r = o.received ?? 0;
    const t = o.total ?? 0;
    return t > 0 && r / t >= 1;
  }).length;

  const poRows = orders
    .map((po) => {
      const received = po.received ?? 0;
      const total = po.total ?? 0;
      const pct = total > 0 ? Math.min((received / total) * 100, 100) : 0;
      const isComplete = pct >= 100;
      const statusLabel = isComplete
        ? 'COMPLETE'
        : pct > 0
        ? 'PARTIAL'
        : (po.status ?? '').toUpperCase() || 'OPEN';

      const barHtml = `<div style="height:6px;background:#f0f0f0;border-radius:3px;overflow:hidden;margin-top:3px"><div style="height:100%;width:${Math.round(pct)}%;background:#0a0a0a;border-radius:3px"></div></div>`;

      const lineItemsHtml =
        po.items && po.items.length > 0
          ? po.items
              .map(
                (item) => {
                  const ir = item.qty_received ?? 0;
                  const io = item.qty_ordered ?? 0;
                  const ip = io > 0 ? Math.min((ir / io) * 100, 100) : 0;
                  return `<tr style="background:#fafafa">
                  <td style="padding-left:28px;color:#666">${item.item_name ?? '—'}</td>
                  <td></td><td></td><td></td>
                  <td class="right">${ir.toLocaleString()} ${item.unit ?? ''}</td>
                  <td class="right">${io.toLocaleString()} ${item.unit ?? ''}</td>
                  <td class="right">${Math.round(ip)}%</td>
                </tr>`;
                },
              )
              .join('')
          : '';

      return `<tr class="group">
        <td>${po.po_number ?? `PO-${po.id}`}</td>
        <td>${po.vendor ?? '—'}</td>
        <td>${po.dt ? formatDate(po.dt) : '—'}</td>
        <td>${statusLabel}</td>
        <td class="right">${formatCurrency(received)}</td>
        <td class="right">${formatCurrency(total)}</td>
        <td class="right">${Math.round(pct)}%${barHtml}</td>
      </tr>${lineItemsHtml}`;
    })
    .join('');

  const body = `
    <div class="report-header">
      <div class="report-title">Goods Receipt Report</div>
      <div class="report-meta">Company: ${companyName} &nbsp;·&nbsp; ${new Date().toLocaleDateString()}</div>
    </div>

    <div class="summary-grid">
      <div class="summary-block">
        <div class="value">${orders.length}</div>
        <div class="label">Total POs</div>
      </div>
      <div class="summary-block">
        <div class="value">${completePOs}</div>
        <div class="label">Complete</div>
      </div>
      <div class="summary-block">
        <div class="value">${Math.round(overallPct)}%</div>
        <div class="label">Overall Received</div>
      </div>
      <div class="summary-block">
        <div class="value">${formatCurrency(totalReceived)}</div>
        <div class="label">Value Received</div>
      </div>
    </div>

    <div class="section-label">Receipt Status by Purchase Order</div>
    <table>
      <thead>
        <tr>
          <th>PO #</th>
          <th>Vendor</th>
          <th>Date</th>
          <th>Status</th>
          <th class="right">Received</th>
          <th class="right">Ordered</th>
          <th class="right">Progress</th>
        </tr>
      </thead>
      <tbody>
        ${poRows || '<tr><td colspan="7" class="muted">No GRN data found</td></tr>'}
      </tbody>
    </table>
  `;

  const filename = `grn-report-${new Date().toISOString().split('T')[0]}.pdf`;
  await printAndShare(wrapHtml('Goods Receipt Report', body), filename);
}
