import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Alert } from 'react-native';
import type { TrialBalanceRow } from '@/api/trialBalance';
import type { JournalEntry } from '@/api/journalEntries';
import { formatCurrency } from '@/utils/currency';

// ─── shared HTML helpers ───────────────────────────────────────────────────

const BASE_CSS = `
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: -apple-system, 'Helvetica Neue', Arial, sans-serif;
    font-size: 11px;
    color: #0a0a0a;
    background: #fff;
    padding: 32px 36px;
  }
  .report-header { margin-bottom: 20px; }
  .report-title { font-size: 18px; font-weight: 800; letter-spacing: -0.3px; }
  .report-meta { font-size: 11px; color: #666; margin-top: 4px; }
  .summary-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 12px;
    margin: 16px 0;
  }
  .summary-block {
    border: 1px solid #e8e8e8;
    border-radius: 6px;
    padding: 12px 14px;
  }
  .summary-block .value { font-size: 15px; font-weight: 700; }
  .summary-block .label { font-size: 10px; color: #888; margin-top: 3px; }
  .net-row {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 10px 14px;
    border: 1px solid #0a0a0a;
    border-radius: 6px;
    margin: 8px 0 20px;
  }
  .net-label { font-size: 12px; font-weight: 700; }
  .net-value { font-size: 15px; font-weight: 800; }
  .section-label {
    font-size: 10px;
    font-weight: 700;
    letter-spacing: 0.8px;
    color: #888;
    text-transform: uppercase;
    margin: 16px 0 6px;
  }
  table {
    width: 100%;
    border-collapse: collapse;
    border: 1px solid #e8e8e8;
    border-radius: 6px;
    overflow: hidden;
    margin-bottom: 12px;
  }
  thead tr { background: #f5f5f5; }
  th {
    text-align: left;
    padding: 7px 10px;
    font-size: 10px;
    font-weight: 700;
    color: #666;
    border-bottom: 1px solid #e8e8e8;
  }
  th.right { text-align: right; }
  td { padding: 6px 10px; font-size: 11px; border-bottom: 1px solid #f0f0f0; }
  td.right { text-align: right; font-variant-numeric: tabular-nums; }
  td.muted { color: #aaa; }
  tr.group td { font-weight: 700; background: #fafafa; }
  tr.total td {
    font-weight: 700;
    font-size: 12px;
    background: #f5f5f5;
    border-top: 1px solid #e8e8e8;
    border-bottom: none;
  }
  .warning {
    border: 1px solid #e8e8e8;
    border-radius: 6px;
    background: #fafafa;
    padding: 8px 12px;
    font-size: 11px;
    color: #666;
    margin: 8px 0;
  }
  .footer {
    margin-top: 32px;
    padding-top: 12px;
    border-top: 1px solid #e8e8e8;
    font-size: 10px;
    color: #aaa;
    text-align: right;
  }
`;

function wrapHtml(title: string, body: string): string {
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${title}</title>
  <style>${BASE_CSS}</style>
</head>
<body>
  ${body}
  <div class="footer">Generated by Poultry ERP Mobile · ${new Date().toLocaleString()}</div>
</body>
</html>`;
}

async function printAndShare(html: string, filename: string): Promise<void> {
  try {
    const canShare = await Sharing.isAvailableAsync();
    if (canShare) {
      const { uri } = await Print.printToFileAsync({ html, base64: false });
      await Sharing.shareAsync(uri, {
        mimeType: 'application/pdf',
        dialogTitle: filename,
        UTI: 'com.adobe.pdf',
      });
    } else {
      // Fall back to the print dialog on platforms where sharing is unavailable
      await Print.printAsync({ html });
    }
  } catch (e: any) {
    Alert.alert('Export failed', e?.message ?? String(e));
  }
}

// ─── Trial Balance PDF ──────────────────────────────────────────────────────

export async function exportTrialBalancePDF(params: {
  rows: TrialBalanceRow[];
  companyName: string;
  asOf: string;
  totalDebit: number;
  totalCredit: number;
}): Promise<void> {
  const { rows, companyName, asOf, totalDebit, totalCredit } = params;
  const isBalanced = Math.abs(totalDebit - totalCredit) < 0.01;

  const tableRows = rows.map((r) => {
    const indent = (r.level ?? 0) * 16;
    const name = r.account_code ? `${r.account_code} — ${r.account_name ?? ''}` : (r.account_name ?? '');
    const dr = r.debit > 0 ? formatCurrency(r.debit) : '';
    const cr = r.credit > 0 ? formatCurrency(r.credit) : '';
    return `<tr${r.is_group ? ' class="group"' : ''}>
      <td style="padding-left:${10 + indent}px">${name}</td>
      <td class="right${!r.debit ? ' muted' : ''}">${dr || '—'}</td>
      <td class="right${!r.credit ? ' muted' : ''}">${cr || '—'}</td>
    </tr>`;
  }).join('');

  const body = `
    <div class="report-header">
      <div class="report-title">Trial Balance</div>
      <div class="report-meta">Company: ${companyName} &nbsp;·&nbsp; As of: ${asOf}</div>
    </div>

    ${!isBalanced ? `<div class="warning">⚠ Out of balance by ${formatCurrency(Math.abs(totalDebit - totalCredit))}</div>` : ''}

    <table>
      <thead>
        <tr>
          <th>Account</th>
          <th class="right">Debit</th>
          <th class="right">Credit</th>
        </tr>
      </thead>
      <tbody>
        ${tableRows}
        <tr class="total">
          <td>TOTAL</td>
          <td class="right">${formatCurrency(totalDebit)}</td>
          <td class="right">${formatCurrency(totalCredit)}</td>
        </tr>
      </tbody>
    </table>
    ${isBalanced ? '<div class="warning" style="background:#f0faf0">✓ Balanced</div>' : ''}
  `;

  await printAndShare(wrapHtml('Trial Balance', body), 'trial-balance.pdf');
}

// ─── P&L PDF ────────────────────────────────────────────────────────────────

interface PLData {
  revenues: TrialBalanceRow[];
  expenses: TrialBalanceRow[];
  totalRevenue: number;
  totalExpense: number;
  netIncome: number;
}

export async function exportPLPDF(params: {
  pl: PLData;
  companyName: string;
  asOf: string;
}): Promise<void> {
  const { pl, companyName, asOf } = params;

  const revenueRows = pl.revenues.map((r) => `
    <tr>
      <td>${r.account_code ? `${r.account_code} — ` : ''}${r.account_name ?? ''}</td>
      <td class="right">${formatCurrency(Math.abs(r.balance ?? r.credit - r.debit))}</td>
    </tr>`).join('');

  const expenseRows = pl.expenses.map((r) => `
    <tr>
      <td>${r.account_code ? `${r.account_code} — ` : ''}${r.account_name ?? ''}</td>
      <td class="right">${formatCurrency(Math.abs(r.balance ?? r.debit - r.credit))}</td>
    </tr>`).join('');

  const body = `
    <div class="report-header">
      <div class="report-title">Profit &amp; Loss Statement</div>
      <div class="report-meta">Company: ${companyName} &nbsp;·&nbsp; As of: ${asOf}</div>
    </div>

    <div class="summary-grid">
      <div class="summary-block">
        <div class="value">${formatCurrency(pl.totalRevenue)}</div>
        <div class="label">Total Revenue</div>
      </div>
      <div class="summary-block">
        <div class="value">${formatCurrency(pl.totalExpense)}</div>
        <div class="label">Total Expenses</div>
      </div>
    </div>

    <div class="net-row">
      <span class="net-label">Net Income</span>
      <span class="net-value">${formatCurrency(pl.netIncome)}</span>
    </div>

    <div class="section-label">Revenue</div>
    <table>
      <thead><tr><th>Account</th><th class="right">Amount</th></tr></thead>
      <tbody>
        ${revenueRows || '<tr><td colspan="2" class="muted">No revenue accounts</td></tr>'}
        <tr class="total">
          <td>Total Revenue</td>
          <td class="right">${formatCurrency(pl.totalRevenue)}</td>
        </tr>
      </tbody>
    </table>

    <div class="section-label">Expenses</div>
    <table>
      <thead><tr><th>Account</th><th class="right">Amount</th></tr></thead>
      <tbody>
        ${expenseRows || '<tr><td colspan="2" class="muted">No expense accounts</td></tr>'}
        <tr class="total">
          <td>Total Expenses</td>
          <td class="right">${formatCurrency(pl.totalExpense)}</td>
        </tr>
      </tbody>
    </table>
  `;

  await printAndShare(wrapHtml('Profit & Loss', body), 'profit-and-loss.pdf');
}

// ─── Balance Sheet PDF ───────────────────────────────────────────────────────

interface BSData {
  assets: TrialBalanceRow[];
  liabilities: TrialBalanceRow[];
  equity: TrialBalanceRow[];
  totalAssets: number;
  totalLiabilities: number;
  totalEquity: number;
}

function accountTableHtml(rows: TrialBalanceRow[], totalLabel: string, total: number): string {
  const dataRows = rows.map((r) => `
    <tr>
      <td>${r.account_code ? `${r.account_code} — ` : ''}${r.account_name ?? ''}</td>
      <td class="right">${formatCurrency(Math.abs(r.balance ?? Math.abs(r.debit - r.credit)))}</td>
    </tr>`).join('');

  return `
    <table>
      <thead><tr><th>Account</th><th class="right">Amount</th></tr></thead>
      <tbody>
        ${dataRows || '<tr><td colspan="2" class="muted">No accounts found</td></tr>'}
        <tr class="total">
          <td>${totalLabel}</td>
          <td class="right">${formatCurrency(total)}</td>
        </tr>
      </tbody>
    </table>`;
}

export async function exportBSPDF(params: {
  bs: BSData;
  companyName: string;
  asOf: string;
}): Promise<void> {
  const { bs, companyName, asOf } = params;
  const le = bs.totalLiabilities + bs.totalEquity;
  const isBalanced = Math.abs(bs.totalAssets - le) < 0.01;

  const body = `
    <div class="report-header">
      <div class="report-title">Balance Sheet</div>
      <div class="report-meta">Company: ${companyName} &nbsp;·&nbsp; As of: ${asOf}</div>
    </div>

    <div class="summary-grid">
      <div class="summary-block">
        <div class="value">${formatCurrency(bs.totalAssets)}</div>
        <div class="label">Total Assets</div>
      </div>
      <div class="summary-block">
        <div class="value">${formatCurrency(le)}</div>
        <div class="label">Liabilities + Equity</div>
      </div>
    </div>

    ${!isBalanced ? `<div class="warning">⚠ Out of balance by ${formatCurrency(Math.abs(bs.totalAssets - le))}</div>` : ''}

    <div class="section-label">Assets</div>
    ${accountTableHtml(bs.assets, 'Total Assets', bs.totalAssets)}

    <div class="section-label">Liabilities</div>
    ${accountTableHtml(bs.liabilities, 'Total Liabilities', bs.totalLiabilities)}

    <div class="section-label">Equity</div>
    ${accountTableHtml(bs.equity, 'Total Equity', bs.totalEquity)}

    <div class="net-row">
      <span class="net-label">Total L + E</span>
      <span class="net-value">${formatCurrency(le)}</span>
    </div>
  `;

  await printAndShare(wrapHtml('Balance Sheet', body), 'balance-sheet.pdf');
}

// ─── Combined Financial Reports PDF ─────────────────────────────────────────

function classifyRow(
  row: TrialBalanceRow,
): 'revenue' | 'expense' | 'asset' | 'liability' | 'equity' | null {
  const type = (row.account_type ?? row.account_name ?? '').toLowerCase();
  if (type.includes('revenue') || type.includes('income') || type.includes('sales')) return 'revenue';
  if (type.includes('expense') || type.includes('cost') || type.includes('cogs')) return 'expense';
  if (
    type.includes('asset') ||
    type.includes('receivable') ||
    type.includes('inventory') ||
    type.includes('cash')
  )
    return 'asset';
  if (type.includes('liability') || type.includes('payable') || type.includes('loan'))
    return 'liability';
  if (type.includes('equity') || type.includes('capital') || type.includes('retained'))
    return 'equity';
  return null;
}

const COMBINED_EXTRA_CSS = `
  .page-break { page-break-before: always; margin: 48px 0 0; border-top: 2px solid #0a0a0a; padding-top: 32px; }
  .report-bundle-cover {
    display: flex;
    flex-direction: column;
    justify-content: center;
    min-height: 200px;
    border: 1px solid #0a0a0a;
    border-radius: 8px;
    padding: 32px 36px;
    margin-bottom: 32px;
  }
  .bundle-title { font-size: 22px; font-weight: 800; letter-spacing: -0.5px; margin-bottom: 8px; }
  .bundle-meta { font-size: 12px; color: #555; line-height: 1.8; }
  .toc { margin-top: 20px; }
  .toc-item {
    display: flex;
    align-items: baseline;
    gap: 8px;
    padding: 6px 0;
    border-bottom: 1px solid #f0f0f0;
    font-size: 12px;
  }
  .toc-num { font-weight: 700; color: #888; width: 20px; }
  .toc-label { flex: 1; }
`;

export async function exportCombinedReportPDF(params: {
  rows: TrialBalanceRow[];
  companyName: string;
  asOf: string;
  totalDebit: number;
  totalCredit: number;
}): Promise<void> {
  const { rows, companyName, asOf, totalDebit, totalCredit } = params;

  // Classify rows
  const revenues = rows.filter((r) => classifyRow(r) === 'revenue');
  const expenses = rows.filter((r) => classifyRow(r) === 'expense');
  const assets = rows.filter((r) => classifyRow(r) === 'asset');
  const liabilities = rows.filter((r) => classifyRow(r) === 'liability');
  const equity = rows.filter((r) => classifyRow(r) === 'equity');

  const totalRevenue = revenues.reduce((s, r) => s + Math.abs(r.balance ?? r.credit - r.debit), 0);
  const totalExpense = expenses.reduce((s, r) => s + Math.abs(r.balance ?? r.debit - r.credit), 0);
  const netIncome = totalRevenue - totalExpense;
  const totalAssets = assets.reduce((s, r) => s + Math.abs(r.balance ?? r.debit - r.credit), 0);
  const totalLiabilities = liabilities.reduce(
    (s, r) => s + Math.abs(r.balance ?? r.credit - r.debit),
    0,
  );
  const totalEquity = equity.reduce((s, r) => s + Math.abs(r.balance ?? r.credit - r.debit), 0);
  const le = totalLiabilities + totalEquity;
  const isTBBalanced = Math.abs(totalDebit - totalCredit) < 0.01;
  const isBSBalanced = Math.abs(totalAssets - le) < 0.01;

  // TB rows HTML
  const tbRowsHtml = rows
    .map((r) => {
      const indent = (r.level ?? 0) * 16;
      const name = r.account_code
        ? `${r.account_code} — ${r.account_name ?? ''}`
        : (r.account_name ?? '');
      const dr = r.debit > 0 ? formatCurrency(r.debit) : '';
      const cr = r.credit > 0 ? formatCurrency(r.credit) : '';
      return `<tr${r.is_group ? ' class="group"' : ''}>
        <td style="padding-left:${10 + indent}px">${name}</td>
        <td class="right${!r.debit ? ' muted' : ''}">${dr || '—'}</td>
        <td class="right${!r.credit ? ' muted' : ''}">${cr || '—'}</td>
      </tr>`;
    })
    .join('');

  // Helper for single-amount account rows
  const accountRows = (accs: TrialBalanceRow[], totalLabel: string, total: number) => {
    const rows2 = accs
      .map(
        (r) => `<tr>
        <td>${r.account_code ? `${r.account_code} — ` : ''}${r.account_name ?? ''}</td>
        <td class="right">${formatCurrency(Math.abs(r.balance ?? Math.abs(r.debit - r.credit)))}</td>
      </tr>`,
      )
      .join('');
    return `<table>
      <thead><tr><th>Account</th><th class="right">Amount</th></tr></thead>
      <tbody>
        ${rows2 || '<tr><td colspan="2" class="muted">No accounts</td></tr>'}
        <tr class="total"><td>${totalLabel}</td><td class="right">${formatCurrency(total)}</td></tr>
      </tbody>
    </table>`;
  };

  const meta = `Company: ${companyName} &nbsp;·&nbsp; As of: ${asOf}`;

  const body = `
    <!-- Cover -->
    <div class="report-bundle-cover">
      <div class="bundle-title">Financial Reports Bundle</div>
      <div class="bundle-meta">
        <div>Company: <strong>${companyName}</strong></div>
        <div>As of: <strong>${asOf}</strong></div>
        <div>Generated: ${new Date().toLocaleDateString()}</div>
      </div>
      <div class="toc">
        <div class="toc-item"><span class="toc-num">1</span><span class="toc-label">Trial Balance</span></div>
        <div class="toc-item"><span class="toc-num">2</span><span class="toc-label">Profit &amp; Loss Statement</span></div>
        <div class="toc-item"><span class="toc-num">3</span><span class="toc-label">Balance Sheet</span></div>
      </div>
    </div>

    <!-- 1. Trial Balance -->
    <div class="report-header">
      <div class="report-title">1 &nbsp; Trial Balance</div>
      <div class="report-meta">${meta}</div>
    </div>
    ${!isTBBalanced ? `<div class="warning">Out of balance by ${formatCurrency(Math.abs(totalDebit - totalCredit))}</div>` : ''}
    <table>
      <thead><tr><th>Account</th><th class="right">Debit</th><th class="right">Credit</th></tr></thead>
      <tbody>
        ${tbRowsHtml}
        <tr class="total">
          <td>TOTAL</td>
          <td class="right">${formatCurrency(totalDebit)}</td>
          <td class="right">${formatCurrency(totalCredit)}</td>
        </tr>
      </tbody>
    </table>
    ${isTBBalanced ? '<div class="warning" style="background:#f0faf0">✓ Balanced</div>' : ''}

    <!-- 2. Profit & Loss -->
    <div class="page-break">
      <div class="report-title">2 &nbsp; Profit &amp; Loss Statement</div>
      <div class="report-meta">${meta}</div>
    </div>
    <div class="summary-grid" style="margin-top:16px">
      <div class="summary-block">
        <div class="value">${formatCurrency(totalRevenue)}</div>
        <div class="label">Total Revenue</div>
      </div>
      <div class="summary-block">
        <div class="value">${formatCurrency(totalExpense)}</div>
        <div class="label">Total Expenses</div>
      </div>
    </div>
    <div class="net-row">
      <span class="net-label">Net Income</span>
      <span class="net-value">${formatCurrency(netIncome)}</span>
    </div>
    <div class="section-label">Revenue</div>
    ${accountRows(revenues, 'Total Revenue', totalRevenue)}
    <div class="section-label">Expenses</div>
    ${accountRows(expenses, 'Total Expenses', totalExpense)}

    <!-- 3. Balance Sheet -->
    <div class="page-break">
      <div class="report-title">3 &nbsp; Balance Sheet</div>
      <div class="report-meta">${meta}</div>
    </div>
    <div class="summary-grid" style="margin-top:16px">
      <div class="summary-block">
        <div class="value">${formatCurrency(totalAssets)}</div>
        <div class="label">Total Assets</div>
      </div>
      <div class="summary-block">
        <div class="value">${formatCurrency(le)}</div>
        <div class="label">Liabilities + Equity</div>
      </div>
    </div>
    ${!isBSBalanced ? `<div class="warning">Out of balance by ${formatCurrency(Math.abs(totalAssets - le))}</div>` : ''}
    <div class="section-label">Assets</div>
    ${accountRows(assets, 'Total Assets', totalAssets)}
    <div class="section-label">Liabilities</div>
    ${accountRows(liabilities, 'Total Liabilities', totalLiabilities)}
    <div class="section-label">Equity</div>
    ${accountRows(equity, 'Total Equity', totalEquity)}
    <div class="net-row">
      <span class="net-label">Total L + E</span>
      <span class="net-value">${formatCurrency(le)}</span>
    </div>
  `;

  // Inject extra CSS into the combined wrapper
  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Financial Reports Bundle</title>
  <style>${BASE_CSS}${COMBINED_EXTRA_CSS}</style>
</head>
<body>
  ${body}
  <div class="footer">Generated by Poultry ERP Mobile · ${new Date().toLocaleString()}</div>
</body>
</html>`;

  await printAndShare(html, 'financial-reports-bundle.pdf');
}

// ─── Journal Entries PDF ─────────────────────────────────────────────────────

export async function exportJournalEntriesPDF(params: {
  entries: JournalEntry[];
  companyName: string;
  type: string;
  from?: string;
  to?: string;
}): Promise<void> {
  const { entries, companyName, type, from, to } = params;

  const entryRows = entries.map((e) => {
    const lineRows = (e.lines ?? []).map((l) => `
      <tr>
        <td style="padding-left:24px;color:#555">${l.account ?? ''}</td>
        <td class="right">${l.debit ? formatCurrency(l.debit) : ''}</td>
        <td class="right">${l.credit ? formatCurrency(l.credit) : ''}</td>
      </tr>`).join('');

    return `
      <tr class="group">
        <td>
          <span style="font-weight:700">${e.voucher_type ?? ''} ${e.voucher_no ?? ''}</span>
          <span style="font-weight:400;color:#888;margin-left:8px">${e.dt ?? ''}</span>
        </td>
        <td class="right">${e.total_debit ? formatCurrency(e.total_debit) : ''}</td>
        <td class="right">${e.total_credit ? formatCurrency(e.total_credit) : ''}</td>
      </tr>
      ${e.narration ? `<tr><td colspan="3" style="color:#777;padding-left:12px;font-style:italic">${e.narration}</td></tr>` : ''}
      ${lineRows}`;
  }).join('');

  const metaParts = [companyName];
  if (type !== 'All') metaParts.push(`Type: ${type}`);
  if (from) metaParts.push(`From: ${from}`);
  if (to) metaParts.push(`To: ${to}`);

  const body = `
    <div class="report-header">
      <div class="report-title">Journal Entries</div>
      <div class="report-meta">${metaParts.join(' &nbsp;·&nbsp; ')}</div>
    </div>

    <div class="summary-grid">
      <div class="summary-block">
        <div class="value">${entries.length}</div>
        <div class="label">Total Vouchers</div>
      </div>
      <div class="summary-block">
        <div class="value">${formatCurrency(entries.reduce((s, e) => s + (e.total_debit ?? 0), 0))}</div>
        <div class="label">Total Amount</div>
      </div>
    </div>

    <table>
      <thead>
        <tr>
          <th>Voucher / Account</th>
          <th class="right">Debit</th>
          <th class="right">Credit</th>
        </tr>
      </thead>
      <tbody>
        ${entryRows || '<tr><td colspan="3" class="muted">No entries</td></tr>'}
      </tbody>
    </table>
  `;

  await printAndShare(wrapHtml('Journal Entries', body), 'journal-entries.pdf');
}
