const {
  Document, Packer, Paragraph, TextRun, HeadingLevel,
  Table, TableRow, TableCell, WidthType, BorderStyle,
  AlignmentType, ShadingType,
} = require("docx");
const fs = require("fs");

const BLUE = "0A6ED1";
const DARK = "1D2D3E";
const GRAY = "546E7A";
const LIGHT_BG = "F0F4F8";
const WHITE = "FFFFFF";
const GREEN = "2E7D32";

function heading(text, level = HeadingLevel.HEADING_1) {
  return new Paragraph({ heading: level, spacing: { before: 300, after: 120 }, children: [new TextRun({ text, bold: true, color: DARK })] });
}

function body(text, opts = {}) {
  return new Paragraph({ spacing: { after: 80 }, children: [new TextRun({ text, size: 22, color: opts.color || DARK, ...opts })] });
}

function bullet(text, level = 0) {
  return new Paragraph({ bullet: { level }, spacing: { after: 40 }, children: [new TextRun({ text, size: 22, color: DARK })] });
}

function tableCell(text, opts = {}) {
  return new TableCell({
    width: opts.width ? { size: opts.width, type: WidthType.PERCENTAGE } : undefined,
    shading: opts.header ? { type: ShadingType.SOLID, color: BLUE } : opts.alt ? { type: ShadingType.SOLID, color: LIGHT_BG } : undefined,
    children: [new Paragraph({ spacing: { before: 40, after: 40 }, children: [new TextRun({ text, size: 20, bold: !!opts.header, color: opts.header ? WHITE : DARK })] })],
  });
}

function tableRow(cells, opts = {}) {
  return new TableRow({ children: cells.map((c, i) => tableCell(c, { ...opts, width: opts.widths?.[i] })) });
}

const doc = new Document({
  creator: "Poultry ERP Team",
  title: "Poultry ERP Mobile App — Feature Documentation",
  description: "Comprehensive documentation of the React Native mobile app for Poultry ERP",
  sections: [{
    properties: {},
    children: [
      // Title
      new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 100 }, children: [new TextRun({ text: "Poultry ERP Mobile App", bold: true, size: 48, color: BLUE })] }),
      new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 40 }, children: [new TextRun({ text: "Feature Documentation & Implementation Guide", size: 28, color: GRAY })] }),
      new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 300 }, children: [new TextRun({ text: `Generated: ${new Date().toISOString().slice(0, 10)}`, size: 20, color: GRAY, italics: true })] }),

      // 1. Overview
      heading("1. Project Overview"),
      body("The Poultry ERP Mobile App is a React Native (Expo) application that provides mobile access to the Poultry ERP system. It connects to the same PostgreSQL backend as the Next.js web application through dedicated REST API endpoints."),
      body(""),
      heading("1.1 Technology Stack", HeadingLevel.HEADING_2),
      bullet("React Native 0.74 with Expo SDK 51"),
      bullet("TypeScript for type safety"),
      bullet("React Navigation 6 (native stack + bottom tabs)"),
      bullet("Expo Secure Store for JWT token storage"),
      bullet("Custom fetch-based API client with cookie auth"),
      body(""),
      heading("1.2 Repository", HeadingLevel.HEADING_2),
      bullet("Mobile App: github.com/haseebahmad24/Poultry-ERP-Mobile"),
      bullet("Web App (Backend): github.com/haseebahmad24/Poultry-ERP-Next-JS"),

      // 2. Architecture
      heading("2. Architecture"),
      heading("2.1 Authentication Flow", HeadingLevel.HEADING_2),
      body("The mobile app uses the same JWT-based authentication as the web app:"),
      bullet("User selects an employee from the login screen"),
      bullet("App calls POST /api/auth/switch with the employee ID"),
      bullet("Server returns a JWT token in the response body"),
      bullet("Token is stored in Expo Secure Store (encrypted device storage)"),
      bullet("All subsequent API calls include the token as Cookie: auth_token=<token>"),
      bullet("AuthContext manages state: loading → unauthenticated → authenticated"),
      body(""),
      heading("2.2 Navigation Architecture (Updated Session 2)", HeadingLevel.HEADING_2),
      body("The app uses a two-level navigation structure:"),
      bullet("AppStack (native stack) — root navigator when authenticated"),
      bullet("  Tabs screen — bottom tab navigator (Dashboard, Inventory, Finance, More)", 1),
      bullet("  Inventory screen — full-screen stock/ledger view pushed from quick actions", 1),
      bullet("  Materials screen — materials list pushed from quick actions", 1),
      bullet("  PurchaseOrders screen — PO list pushed from quick actions", 1),
      bullet("  PODetail screen — PO detail pushed from PO list", 1),
      bullet("AuthNavigator (native stack) — Login screen when unauthenticated"),
      body(""),
      heading("2.3 API Layer", HeadingLevel.HEADING_2),
      body("The web app exposes dedicated REST endpoints under /api/mobile/ for the mobile app. Each endpoint accepts query parameters for filtering and returns JSON. Authentication is required on all endpoints."),
      body(""),

      // API Endpoints Table
      heading("2.4 Backend API Endpoints", HeadingLevel.HEADING_2),
      new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [
          tableRow(["Endpoint", "Method", "Parameters", "Returns"], { header: true, widths: [30, 8, 32, 30] }),
          tableRow(["/api/employees", "GET", "—", "{ employees[] } — user list for login"]),
          tableRow(["/api/auth/switch", "POST", "{ id }", "{ ok, token, user }"], { alt: true }),
          tableRow(["/api/dashboard", "GET", "?company_id", "{ kpis, recentVouchers[] }"]),
          tableRow(["/api/mobile/inventory", "GET", "?view=stock|items|warehouses|uoms|categories|ledger, ?company_id, ?item_id, ?warehouse_id, ?from, ?to", "Stock balances, items, warehouses, ledger entries"], { alt: true }),
          tableRow(["/api/mobile/materials", "GET", "?view=list|types|views, ?company_id, ?type_id, ?status", "Materials list, material types"]),
          tableRow(["/api/mobile/purchase-orders", "GET", "?view=all|open|progress, ?status, ?id", "Purchase orders, PO progress"], { alt: true }),
          tableRow(["/api/mobile/sales-orders", "GET", "?view=open|approved|closed|detail|register, ?id, ?company_id", "Sales orders by status"]),
          tableRow(["/api/mobile/accounts-payable", "GET", "?view=summary|bills|vendors|drafts|due, ?company_id", "AP totals, aging, bills, vendors"], { alt: true }),
          tableRow(["/api/mobile/accounts-receivable", "GET", "?view=summary|invoices|customers|drafts, ?company_id", "AR totals, aging, invoices, customers"]),
          tableRow(["/api/mobile/journal-entries", "GET", "?company_id, ?from, ?to, ?account, ?type", "Journal entries"], { alt: true }),
          tableRow(["/api/mobile/trial-balance", "GET", "?company_id, ?as_of", "Trial balance rows"]),
          tableRow(["/api/mobile/partners", "GET", "?company_id", "Business partners"], { alt: true }),
          tableRow(["/api/mobile/companies", "GET", "—", "Companies list"]),
        ],
      }),

      // 3. Implemented Features
      heading("3. Implemented Features (Sessions 1–2)"),

      heading("3.1.1 Project Scaffolding", HeadingLevel.HEADING_3),
      bullet("Expo 51 / React Native 0.74 project initialized"),
      bullet("TypeScript with @/ path aliases via babel-plugin-module-resolver"),
      bullet("React Navigation with native stack and bottom tab navigators"),
      body(""),

      heading("3.1.2 Design System (src/theme/index.ts)", HeadingLevel.HEADING_3),
      bullet("Full color palette matching web app (primary blue #0A6ED1, greens, reds, oranges)"),
      bullet("Voucher type badge colors (JV, GRN, DN, PAY, REC, INV, SO, PO)"),
      bullet("Spacing scale, border radius tokens, shadow presets, typography scale"),
      body(""),

      heading("3.1.3 API Client (src/api/client.ts)", HeadingLevel.HEADING_3),
      bullet("Fetch wrapper with automatic JWT token attachment"),
      bullet("Token stored/retrieved via expo-secure-store (encrypted device storage)"),
      bullet("Sends Cookie: auth_token=<token> header on all requests"),
      bullet("Configurable base URL via EXPO_PUBLIC_API_URL env var"),
      body(""),

      heading("3.1.4 Auth Context (src/context/AuthContext.tsx)", HeadingLevel.HEADING_3),
      bullet("React context with loginAs / logout actions"),
      bullet("Restores session from stored JWT on app start (decodes payload)"),
      bullet("Three states: loading, unauthenticated, authenticated"),
      bullet("useAuth() hook for consuming components"),
      body(""),

      heading("3.1.5 Login Screen (src/screens/auth/LoginScreen.tsx)", HeadingLevel.HEADING_3),
      bullet("Fetches employee list from /api/employees"),
      bullet("Card list with avatar initials, name, email, role badge"),
      bullet("Tap to login — calls /api/auth/switch, stores JWT token"),
      bullet("Loading and error states with retry button"),
      body(""),

      heading("3.1.6 Dashboard Screen (src/screens/dashboard/DashboardScreen.tsx)", HeadingLevel.HEADING_3),
      bullet("Top bar with time-based greeting, user name/role, sign out button"),
      bullet("Pull-to-refresh support"),
      bullet("3×2 KPI grid: Revenue, Expenses, Net Income, Cash & Bank, Receivables, Payables"),
      bullet("Working Capital panel (Cash + AR − AP = Net)"),
      bullet("Quick Actions grid: wired to Inventory, Materials, Purchase Orders (others disabled until built)"),
      bullet("Recent Activity list (last 20 vouchers with type badge, number, date, amount, status)"),
      body(""),

      heading("3.1.7 Shared Components (src/components/)", HeadingLevel.HEADING_3),
      bullet("LoadingView — centered spinner with optional message"),
      bullet("ErrorView — error message with retry button"),
      bullet("KPICard — metric card (label / value / subtext, optional color)"),
      bullet("SectionHeader — section title with optional right-side meta text"),
      bullet("SkeletonBox — animated shimmer rectangle (pulse animation, any width/height/radius)"),
      bullet("SkeletonListItem — card-shaped skeleton with left column + optional right badge (Session 12)"),
      bullet("SkeletonKPICard — KPI card proportions skeleton (Session 12)"),
      bullet("DashboardSkeleton — full-page dashboard skeleton including top bar (Session 12)"),
      bullet("ListScreenSkeleton — inline skeleton: optional search + tabs + N list items (Session 12)"),
      bullet("FinanceSummarySkeleton — inline skeleton: summary tiles + aging bar + tabs + list (Session 12)"),
      bullet("DetailSkeleton — inline skeleton: summary tiles + section label + N rows (Session 12)"),
      bullet("VoucherActivityChart — horizontal bar chart showing top-6 voucher types by count + amount (Session 13)"),
      bullet("AgingChart — stacked horizontal aging analysis bar with legend (Session 11)"),
      bullet("BiometricLockOverlay — full-screen lock overlay with LocalAuthentication.authenticateAsync(); 'Try Again' state on failure (Session 15)"),
      bullet("OfflineBanner — amber banner shown when displaying stale cached data (Session 6)"),
      bullet("BackButton — navigation back button for stack screens (Session 4)"),
      bullet("CompanySelector — bottom-sheet company picker using global CompanyContext (Session 3)"),
      bullet("DateRangeBar — date range/single date input bar with presets and clear button (Session 8 UI polish)"),
      bullet("SearchBar — reusable search input with icon and clear button"),
      bullet("FilterChip — toggleable pill-shaped filter chip"),
      bullet("StatusBadge — colored status pill (configurable text, bg, fg)"),
      bullet("TabBar — horizontal tab row component"),
      bullet("SegmentedControl — multi-option segmented control"),
      body(""),

      heading("3.10 Inventory Screen (src/screens/inventory/InventoryScreen.tsx)", HeadingLevel.HEADING_2),
      bullet("Three-tab view: Stock Balances, Stock Ledger, Warehouses (Session 5)"),
      bullet("Stock Balances: item/warehouse/qty cards with color-coded quantity levels"),
      bullet("Stock Balances: tappable cards — tap navigates to ItemLedgerScreen for that item (Session 6)"),
      bullet("Stock Balances: All / Low Stock / Out of Stock filter chips with live counts (Session 5)"),
      bullet("Stock Ledger: movement log with IN/OUT/balance amounts and voucher type badges"),
      bullet("Stock Ledger: date range filter with From/To inputs and quick presets (Session 5)"),
      bullet("Warehouses: card list showing warehouse name, code, type, address, active status (Session 5)"),
      bullet("Search filter across all three tabs"),
      bullet("Pull-to-refresh, loading and empty states"),
      bullet("Offline caching: stock balances cached in AsyncStorage, served instantly on next open (Session 6)"),
      bullet("OfflineBanner shown when cached (stale) data is displayed (Session 6)"),
      body(""),

      heading("3.10a Inventory Item Ledger Screen (src/screens/inventory/ItemLedgerScreen.tsx)", HeadingLevel.HEADING_2),
      bullet("New screen introduced in Session 6 — accessible by tapping a stock balance card"),
      bullet("Shows full movement history (IN/OUT/balance) for a single inventory item"),
      bullet("Summary bar: total qty in, total qty out, current balance with color coding"),
      bullet("Date range filter panel with quick presets (Today, This Week, This Month, Last Month)"),
      bullet("Voucher type badges (GRN, SRN, ADJ, TRN, INV) with color coding"),
      bullet("Pull-to-refresh and empty state with clear-filter CTA"),
      body(""),

      heading("3.11 Materials Screen (src/screens/materials/MaterialsScreen.tsx)", HeadingLevel.HEADING_2),
      bullet("Searchable list by name, code, type, category"),
      bullet("Horizontal type filter chips fetched from /api/mobile/materials?view=types"),
      bullet("Material cards: name, code, type badge, status badge (Active/Inactive), unit chip"),
      bullet("Material cards are tappable — navigate to MaterialDetailScreen with full params (Session 13)"),
      bullet("Offline caching: materials + types cached per company+type combo with 24h TTL (Session 7)"),
      body(""),

      heading("3.11a Material Detail Screen (src/screens/materials/MaterialDetailScreen.tsx)", HeadingLevel.HEADING_2),
      bullet("New screen added in Session 13 — accessible by tapping any material card"),
      bullet("Header: material name + optional code badge + meta chips (type, category, unit, status)"),
      bullet("Optional description bar shown below meta chips when description is available"),
      bullet("Summary tiles (2×2): Total Stock, Warehouse Count, Total In, Total Out"),
      bullet("Stock by Warehouse: per-warehouse cards with qty, unit, low-stock/out-of-stock indicators"),
      bullet("Transactions: up to 50 latest ledger entries per item — voucher badge, date, warehouse, qty delta, running balance"),
      bullet("DateRangeBar date filter on transactions: Today/This Week/This Month/Last Month/Custom presets"),
      bullet("API: fetchStockBalances (filtered by item_id) + fetchStockLedger with item_id + date params"),
      bullet("Navigation: MaterialsScreen cards → MaterialDetail; Search results → MaterialDetail; Alerts low-stock → MaterialDetail"),
      bullet("24h offline cache (bypassed when date filter is active); DetailSkeleton loading; ErrorView; pull-to-refresh"),
      body(""),

      heading("3.12 Purchase Orders Screen (src/screens/purchaseOrders/)", HeadingLevel.HEADING_2),
      bullet("Three status tabs: All / Open / In Progress"),
      bullet("PO cards with: PO number, vendor, date, status badge, total amount, progress bar"),
      bullet("Detail screen: PO header, receipt progress bar, line items with qty ordered/received/pending"),
      body(""),

      heading("3.13 Sales Orders Screen (src/screens/salesOrders/)", HeadingLevel.HEADING_2),
      bullet("Four status tabs: All / Open / Approved / Closed"),
      bullet("SO cards with: SO number, customer, date, status badge, total amount"),
      bullet("Detail screen: SO header, line items list, total row"),
      body(""),

      heading("3.14 GRN Screen (src/screens/grn/GRNScreen.tsx)", HeadingLevel.HEADING_2),
      bullet("Goods receipt progress view per purchase order"),
      bullet("Overall summary card: PO count, overall % received, progress bar"),
      bullet("Per-PO cards: receipt progress, optional line item preview"),
      bullet("Tappable cards navigate to PO Detail screen (Session 4)"),
      body(""),

      heading("3.15 Accounts Payable Screen (src/screens/finance/AccountsPayableScreen.tsx)", HeadingLevel.HEADING_2),
      bullet("Three tabs: Summary / Bills / Vendors"),
      bullet("Summary: KPI cards (outstanding, overdue, vendor count, bill count) + aging analysis bars"),
      bullet("Bills: bill cards with status, amounts, due date + search by number/vendor/status (Session 4)"),
      bullet("Bills: overdue bills sorted to top, tab badge shows overdue count, red left border + banner (Session 6)"),
      bullet("Vendors: vendor cards with outstanding/overdue balances + search by name (Session 4)"),
      bullet("Vendors: cards and top-vendor mini-list rows are tappable — navigate to VendorDetailScreen (Session 7)"),
      bullet("Offline caching: summary/bills/vendors cached per company with 24h TTL; OfflineBanner on stale data (Session 7)"),
      body(""),

      heading("3.15a Vendor Detail Screen (src/screens/finance/VendorDetailScreen.tsx)", HeadingLevel.HEADING_2),
      bullet("New screen introduced in Session 7 — accessible by tapping any vendor in AP screen"),
      bullet("Header: vendor name + 'Vendor · Accounts Payable' subtitle"),
      bullet("Summary tiles: Outstanding, Overdue (highlighted), Total Billed, Bill count"),
      bullet("Bill list: all bills for that vendor, sorted overdue-first"),
      bullet("Overdue alert banner on each overdue bill with days-overdue count"),
      bullet("Search bar to filter bills by number or status"),
      bullet("Pull-to-refresh, loading and empty states"),
      body(""),

      heading("3.16 Accounts Receivable Screen (src/screens/finance/AccountsReceivableScreen.tsx)", HeadingLevel.HEADING_2),
      bullet("Three tabs: Summary / Invoices / Customers"),
      bullet("Summary: KPI cards + aging analysis bars (same pattern as AP)"),
      bullet("Invoices: invoice cards with outstanding amounts + search by number/customer/status (Session 4)"),
      bullet("Invoices: overdue invoices sorted to top, tab badge shows overdue count, red left border + banner (Session 6)"),
      bullet("Customers: customer cards with outstanding/overdue balances + search by name (Session 4)"),
      bullet("Customers: cards and top-customer mini-list rows are tappable — navigate to CustomerDetailScreen (Session 7)"),
      bullet("Offline caching: summary/invoices/customers cached per company with 24h TTL; OfflineBanner on stale data (Session 7)"),
      body(""),

      heading("3.16a Customer Detail Screen (src/screens/finance/CustomerDetailScreen.tsx)", HeadingLevel.HEADING_2),
      bullet("New screen introduced in Session 7 — accessible by tapping any customer in AR screen"),
      bullet("Header: customer name + 'Customer · Accounts Receivable' subtitle"),
      bullet("Summary tiles: Outstanding, Overdue (highlighted when > 0), Total Billed, Invoice count"),
      bullet("Invoice list: all invoices for that customer, sorted overdue-first"),
      bullet("Overdue alert banner on each overdue invoice with days-overdue count"),
      bullet("Search bar to filter invoices by number or status"),
      bullet("Pull-to-refresh, loading and empty states"),
      body(""),

      heading("3.17 Journal Entries Screen (src/screens/journalEntries/JournalEntriesScreen.tsx)", HeadingLevel.HEADING_2),
      bullet("Searchable list: voucher number, narration"),
      bullet("Voucher type filter chips (JV, GRN, PAY, REC, INV, SO, PO, DN)"),
      bullet("Cards with colored type badge, status badge (POSTED/DRAFT/VOID), debit/credit totals"),
      bullet("Expandable cards reveal journal lines (account, debit, credit)"),
      bullet("Date range filter with From/To inputs (YYYY-MM-DD) — server-side filtering (Session 4)"),
      bullet("Quick date presets: Today, This Week, This Month, Last Month (Session 4)"),
      bullet("Export button: shares filtered entries as formatted text via Share API (Session 5)"),
      body(""),

      heading("3.18 Trial Balance Screen (src/screens/trialBalance/TrialBalanceScreen.tsx)", HeadingLevel.HEADING_2),
      bullet("Company selector dropdown (populated from /api/options/companies)"),
      bullet("As-of date text input (YYYY-MM-DD format, Run Report button)"),
      bullet("Account search filter"),
      bullet("Summary card: total debit / total credit with balance diff warning"),
      bullet("Hierarchical account table with group headers, level-based indentation"),
      bullet("Export button: shares trial balance as formatted columnar text report (Session 5)"),
      bullet("Offline caching: serves cached data instantly on mount, refreshes in background; OfflineBanner on stale+error (Session 15)"),
      bullet("Cache key: trial-balance:<companyId>:<asOf> — shared with Financial Reports (same endpoint) (Session 15)"),
      body(""),

      heading("3.19 Business Partners Screen (src/screens/partners/PartnersScreen.tsx)", HeadingLevel.HEADING_2),
      bullet("Searchable list (name, code, email)"),
      bullet("Role filter tabs: All / Customers / Vendors"),
      bullet("Partner cards: avatar initials, name, code, role badges, contact info — tappable (Session 8)"),
      bullet("Tap partner card → PartnerDetailScreen with chevron-right affordance (Session 8)"),
      bullet("Offline caching: partners list cached per company with 24h TTL; OfflineBanner on stale data (Session 8)"),
      body(""),

      heading("3.19a Partner Detail Screen (src/screens/partners/PartnerDetailScreen.tsx)", HeadingLevel.HEADING_2),
      bullet("New screen introduced in Session 8 — accessible by tapping any partner in Partners screen"),
      bullet("Receives: partnerId, partnerName, isVendor, isCustomer navigation params"),
      bullet("Fetches all POs and SOs, then filters client-side by vendor_id / customer_id or matching name"),
      bullet("Summary tiles: Total PO value + order count (for vendors) / Total SO value + order count (for customers)"),
      bullet("Dual-role tab bar (Purchase Orders | Sales Orders) shown when partner has both roles"),
      bullet("PO cards tap → PurchaseOrderDetail; SO cards tap → SalesOrderDetail"),
      bullet("Pull-to-refresh, loading state, empty states per section"),
      body(""),

      heading("3.19b Settings Screen (src/screens/settings/SettingsScreen.tsx)", HeadingLevel.HEADING_2),
      bullet("New screen introduced in Session 8 — accessible from MoreMenu → Admin → Settings"),
      bullet("Low-stock threshold: text input to configure qty threshold for low-stock flag on Inventory screen"),
      bullet("Threshold stored in AsyncStorage via src/utils/settings.ts (getLowStockThreshold/setLowStockThreshold)"),
      bullet("Default threshold: 100 units; validation requires positive integer"),
      bullet("Save button shows check icon feedback for 2s after successful save"),
      bullet("Clear cached data: destructive action with Alert confirmation — removes all cache:* AsyncStorage keys"),
      bullet("About section: app name and version"),
      body(""),

      heading("3.20 Companies Screen (src/screens/companies/CompaniesScreen.tsx)", HeadingLevel.HEADING_2),
      bullet("Company list with logo circle (initial letter), name, code, active/inactive status badge"),
      bullet("Detail grid: currency, fiscal year, phone, email, address"),
      body(""),

      heading("3.21 Financial Reports Screen (src/screens/financialReports/)", HeadingLevel.HEADING_2),
      bullet("Two tabs: Profit & Loss / Balance Sheet"),
      bullet("P&L: revenue vs expense sections, net income summary card"),
      bullet("Balance Sheet: assets, liabilities, equity sections with balance check warning"),
      bullet("Company selector + as-of date picker (same pattern as Trial Balance)"),
      bullet("Accounts classified by account_type keyword matching"),
      bullet("Export button: shares P&L or Balance Sheet as formatted text report (Session 5)"),
      bullet("Offline caching: shares the same trial-balance:<companyId>:<asOf> cache key as Trial Balance; serves data instantly on mount (Session 15)"),
      body(""),

      heading("3.22 Global Company Filter (Updated Session 3)", HeadingLevel.HEADING_2),
      bullet("CompanyContext (src/context/CompanyContext.tsx) — global state: companies list, selectedCompany, companyId"),
      bullet("CompanyPicker (src/components/CompanyPicker.tsx) — horizontal scrollable company chips"),
      bullet("CompanyProvider wrapped around app in App.tsx"),
      bullet("Now applied to all data screens: Dashboard, Inventory, Materials, Journal Entries, Partners, Sales Orders, AP, AR"),
      bullet("TrialBalance and FinancialReports use companies list from context (no duplicate API calls)"),
      bullet("CompanyContext re-loads after login (was incorrectly loading before auth on app start)"),
      body(""),

      heading("3.23 Navigation Architecture (Updated Session 10)", HeadingLevel.HEADING_2),
      bullet("AppStack (native stack) — thin root wrapper, contains only the Tabs screen"),
      bullet("AppNavigator (bottom tabs): Dashboard, Inventory, Finance, More"),
      bullet("  Finance tab: badge showing totalOverdue count (from OverdueContext)", 1),
      bullet("InventoryNavigator (stack, Session 6): InventoryMain → ItemLedger (item detail screen)"),
      bullet("FinanceNavigator (stack): FinanceMenu → AccountsPayable, AccountsReceivable, VendorDetail, CustomerDetail, JournalEntries, TrialBalance, FinancialReports"),
      bullet("MoreNavigator (stack, updated Session 11): MoreMenu → Search, Materials, PurchaseOrders, PurchaseOrderDetail, SalesOrders, SalesOrderDetail, GRN, Partners, PartnerDetail, Companies, Settings, Alerts"),
      bullet("MoreMenu Finance section navigates to Finance tab's real screens via getParent()"),
      bullet("Dashboard Quick Actions wired to real screens via tab navigation"),
      body(""),

      heading("3.25 Offline Caching (Sessions 6–9)", HeadingLevel.HEADING_2),
      bullet("Installed @react-native-async-storage/async-storage for persistent offline storage"),
      bullet("src/utils/cache.ts: getCached(key) → {data, stale} | null; setCached(key, data); clearCache(prefix)"),
      bullet("24-hour TTL per cache entry; versioned entries to invalidate stale schema on updates"),
      bullet("DashboardScreen: loads cached KPIs/vouchers instantly on mount, then fetches fresh in background"),
      bullet("InventoryScreen: caches stock balances per company; shows cached data immediately then refreshes"),
      bullet("AccountsPayableScreen: caches summary/bills/vendors bundle per company (Session 7)"),
      bullet("AccountsReceivableScreen: caches summary/invoices/customers bundle per company (Session 7)"),
      bullet("MaterialsScreen: caches materials+types per company+type combo (Session 7)"),
      bullet("PurchaseOrdersScreen: caches PO list per tab (all/open/progress) with 24h TTL (Session 8)"),
      bullet("SalesOrdersScreen: caches SO list per tab+company combination with 24h TTL (Session 8)"),
      bullet("PartnersScreen: caches partners list per company with 24h TTL (Session 8)"),
      bullet("GRNScreen: caches GRN progress data per company with 24h TTL (Session 9)"),
      bullet("CompaniesScreen: caches companies list (Session 9)"),
      bullet("PODetailScreen + PurchaseOrderDetailScreen: each cache individual PO detail by ID (Session 9)"),
      bullet("SalesOrderDetailScreen: caches individual SO detail by ID (Session 9)"),
      bullet("OfflineBanner (src/components/OfflineBanner.tsx): shown when stale data is displayed on error"),
      bullet("Architecture: try cache → show if found → fetch fresh → update UI + cache; on failure: show cached + banner"),
      body(""),

      heading("3.26 User Preferences / Settings (Sessions 8, 14–16)", HeadingLevel.HEADING_2),
      bullet("src/utils/settings.ts: getLowStockThreshold() / setLowStockThreshold(n) — AsyncStorage backed (Session 8)"),
      bullet("src/utils/settings.ts: getAutoRefreshInterval() / setAutoRefreshInterval(n) — dashboard auto-refresh in minutes; 0=off (Session 14)"),
      bullet("src/utils/settings.ts: getSessionTimeout() / setSessionTimeout(n) — inactivity lock in minutes; 0=off (Session 14)"),
      bullet("src/utils/settings.ts: getBiometricEnabled() / setBiometricEnabled(bool) — biometric lock toggle (Session 15)"),
      bullet("src/utils/settings.ts: getNotificationHour() / setNotificationHour(hour) — notification fire hour 0–23; default 9 (Session 16)"),
      bullet("src/utils/settings.ts: getNotifyApOverdue() / setNotifyApOverdue(bool) — AP overdue alert type toggle; default true (Session 16)"),
      bullet("src/utils/settings.ts: getNotifyArOverdue() / setNotifyArOverdue(bool) — AR overdue alert type toggle; default true (Session 16)"),
      bullet("src/utils/settings.ts: getNotifyLowStock() / setNotifyLowStock(bool) — low-stock alert type toggle; default true (Session 16)"),
      bullet("InventoryScreen: loads low-stock threshold from settings on mount (was hardcoded = 100)"),
      bullet("SettingsScreen: UI to view/edit low-stock threshold, clear all cached data, view app version (Session 8)"),
      bullet("SettingsScreen (Session 14): DASHBOARD section — auto-refresh interval chip picker (Off/1m/5m/10m/30m)"),
      bullet("SettingsScreen (Session 14): SECURITY section — session timeout chip picker (Off/5m/15m/30m/1hr)"),
      bullet("SettingsScreen (Session 15): Biometric lock Switch (only shown when device has enrolled biometrics)"),
      bullet("SettingsScreen (Session 16): NOTIFICATIONS section — master toggle + time picker + 3 per-type Switches"),
      body(""),

      heading("3.34 Biometric Lock (Session 15)", HeadingLevel.HEADING_2),
      bullet("Install: expo-local-authentication"),
      bullet("BiometricLockOverlay (src/components/BiometricLockOverlay.tsx): full-screen overlay shown when app is locked"),
      bullet("  Immediately triggers LocalAuthentication.authenticateAsync() on mount", 1),
      bullet("  Shows lock icon + 'Unlock' button; 'Try Again' state when authentication fails or is cancelled", 1),
      bullet("  Calls onUnlock() callback when auth succeeds — parent dismisses the overlay", 1),
      bullet("AppNavigator: AppState listener detects background → foreground transition"),
      bullet("  Reads getBiometricEnabled() on each foreground event", 1),
      bullet("  Sets biometricLocked=true when enabled; BiometricLockOverlay renders as absolute-fill overlay", 1),
      bullet("  Overlay sits above the tab navigator; does not interrupt navigation state", 1),
      bullet("SettingsScreen: Switch toggle in SECURITY section; requires one successful auth to enable (prevents accidental lockout)"),
      body(""),

      heading("3.35 Local Push Notifications (Sessions 15–16)", HeadingLevel.HEADING_2),
      bullet("Install: expo-notifications v56"),
      bullet("src/utils/notifications.ts: notification helper module"),
      bullet("  setNotificationHandler: banner + list display; no sound; no badge", 1),
      bullet("  requestNotificationPermissions(): checks existing grant, requests if needed, returns boolean", 1),
      bullet("  scheduleOverdueReminder({ apOverdue, arOverdue, lowStock }): schedules daily notification at configured hour", 1),
      bullet("    — Reads per-type settings (notifyApOverdue, notifyArOverdue, notifyLowStock) and notificationHour before composing", 2),
      bullet("    — Skips disabled alert types from the notification body; cancels if effective total = 0", 2),
      bullet("    — Schedules for next occurrence of the configured hour (advances to next day if already past)", 2),
      bullet("    — Fails silently when run in Expo Go or without valid notification credentials", 2),
      bullet("  cancelOverdueReminder(): cancels the scheduled overdue reminder", 1),
      bullet("  getNotificationsEnabled() / setNotificationsEnabled(): AsyncStorage-backed master toggle", 1),
      bullet("AppNavigator: useEffect on [apOverdue, arOverdue, lowStock] — reschedules reminder when alert counts change"),
      bullet("AppNavigator: Notifications.addNotificationResponseReceivedListener — tapping notification navigates to Alerts screen (Session 16)"),
      bullet("SettingsScreen NOTIFICATIONS section (Session 16):"),
      bullet("  Master toggle: 'Overdue reminders' Switch — enables daily notification when alerts exist", 1),
      bullet("  Notification time: 8 chip options (6 AM → 6 PM) — fires reminder at selected hour (Session 16)", 1),
      bullet("  'Notify about' section with 3 per-type Switches: Overdue bills (AP) / Overdue invoices (AR) / Low-stock items (Session 16)", 1),
      bullet("  Per-type controls only visible when master toggle is on (Session 16)", 1),
      body(""),

      heading("3.36 Deep Link Navigation (Session 16)", HeadingLevel.HEADING_2),
      bullet("app.json: added scheme: 'poultryerp' — enables poultryerp:// custom URL scheme on iOS and Android"),
      bullet("Install: expo-linking"),
      bullet("src/navigation/linking.ts: LinkingOptions config mapping poultryerp:// URLs to screen names"),
      bullet("  poultryerp://dashboard → Dashboard tab"),
      bullet("  poultryerp://inventory → InventoryMain (Inventory tab)", 1),
      bullet("  poultryerp://finance → Finance tab menu", 1),
      bullet("  poultryerp://finance/ap → AccountsPayable", 1),
      bullet("  poultryerp://finance/ar → AccountsReceivable", 1),
      bullet("  poultryerp://finance/journal → JournalEntries", 1),
      bullet("  poultryerp://finance/trial-balance → TrialBalance", 1),
      bullet("  poultryerp://finance/reports → FinancialReports", 1),
      bullet("  poultryerp://materials → Materials screen", 1),
      bullet("  poultryerp://purchase-orders → PurchaseOrders screen", 1),
      bullet("  poultryerp://sales-orders → SalesOrders screen", 1),
      bullet("  poultryerp://grn → GRN screen", 1),
      bullet("  poultryerp://partners → Partners screen", 1),
      bullet("  poultryerp://companies → Companies screen", 1),
      bullet("  poultryerp://alerts → Alerts screen", 1),
      bullet("  poultryerp://settings → Settings screen", 1),
      bullet("  poultryerp://search → Search screen", 1),
      bullet("RootNavigator: linking config injected into NavigationContainer when user is authenticated"),
      body(""),

      heading("3.37 PDF Export (Session 16)", HeadingLevel.HEADING_2),
      bullet("Install: expo-print + expo-sharing"),
      bullet("src/utils/pdfExport.ts: shared PDF generation and sharing utility"),
      bullet("  BASE_CSS: monochrome print stylesheet (clean, no colors — matches app design)"),
      bullet("  wrapHtml(title, body): wraps HTML body in full page template with CSS and generated-by footer"),
      bullet("  printAndShare(html, filename): expo-print renders PDF to temp file; expo-sharing opens OS share sheet"),
      bullet("    — Falls back to expo-print.printAsync (system print dialog) when sharing is unavailable", 1),
      bullet("    — Catches all errors and shows Alert to user", 1),
      bullet("  exportTrialBalancePDF: styled account table with debit/credit columns, group rows, totals, balanced status"),
      bullet("  exportPLPDF: summary grid + revenue and expense account tables + Net Income row"),
      bullet("  exportBSPDF: assets / liabilities / equity tables + L+E total row + imbalance warning"),
      bullet("  exportJournalEntriesPDF: summary grid (voucher count + total amount) + full entry table with narration and line items"),
      bullet("TrialBalanceScreen: PDF button (file-text icon) added to header alongside existing Share text button"),
      bullet("FinancialReportsScreen: PDF button added; dispatches to exportPLPDF or exportBSPDF based on active tab"),
      bullet("JournalEntriesScreen: PDF button added alongside existing Share text button"),
      body(""),

      heading("3.31 Dashboard Auto-Refresh + Last Updated (Session 14)", HeadingLevel.HEADING_2),
      bullet("Dashboard load() has isSilent flag — auto-refresh runs in background without showing RefreshControl"),
      bullet("useFocusEffect re-reads refresh interval on every Dashboard focus to pick up changes from Settings"),
      bullet("setInterval fires load(true, true) at configured interval; cleared on unmount or interval change"),
      bullet("lastUpdated: Date state tracks successful fetches — shown in top bar as 'Updated X min ago'"),
      bullet("60-second tick timer keeps the relative-time label fresh without extra API calls"),
      bullet("'Auto ↻Xm' indicator displayed in subGreeting line when auto-refresh is active"),
      body(""),

      heading("3.32 Company Selection Persistence (Session 14)", HeadingLevel.HEADING_2),
      bullet("CompanyContext.setSelectedCompany wraps setSelectedCompanyState: saves company ID to AsyncStorage on every change"),
      bullet("AsyncStorage key: setting:selectedCompanyId"),
      bullet("On app restart, load() reads saved ID alongside companies list and restores previous selection"),
      bullet("Falls back to first company in list when saved ID is absent or no longer available"),
      body(""),

      heading("3.33 Session Timeout / Security Lock (Session 14)", HeadingLevel.HEADING_2),
      bullet("src/hooks/useSessionTimeout.ts: hook using React Native AppState API (no extra packages)"),
      bullet("Records backgroundedAt timestamp when app moves to background/inactive state"),
      bullet("Re-reads the session timeout setting on each background event (picks up changes from Settings)"),
      bullet("On foreground: computes elapsed minutes; calls onTimeout() when elapsed >= configured timeout"),
      bullet("AppNavigator wires useSessionTimeout(logout) — runs for all authenticated screens globally"),
      bullet("SettingsScreen: SECURITY section with chip picker for 0/5/15/30/60 minute options"),
      body(""),

      heading("3.29 Global Search Screen (Session 11)", HeadingLevel.HEADING_2),
      bullet("SearchScreen (src/screens/search/SearchScreen.tsx):"),
      bullet("  Unified search across 5 data types: Purchase Orders, Sales Orders, Stock Balances, Materials, Business Partners", 1),
      bullet("  Loads all data sources on mount (cache-first, background refresh for stale data)", 1),
      bullet("  Instant client-side filtering — no API call on each keystroke", 1),
      bullet("  Results grouped by type with section headers, icon, result count", 1),
      bullet("  Each result shows title, subtitle, optional amount/qty meta, and status badge", 1),
      bullet("  Tapping PO → PurchaseOrderDetail; SO → SalesOrderDetail; Partner → PartnerDetail", 1),
      bullet("  Stock results use cross-tab navigation to Inventory > ItemLedger", 1),
      bullet("  Material results navigate to MaterialsScreen (no per-item detail screen)", 1),
      bullet("  Loading / empty query / zero-results states with Feather icons", 1),
      bullet("  Auto-focuses TextInput on mount; clear (×) button; keyboard-aware FlatList", 1),
      bullet("MoreNavigator: added Search route to MoreStackParamList and navigator"),
      bullet("MoreMenuScreen: tappable search shortcut bar above scroll content navigates to SearchScreen"),
      bullet("DashboardScreen: search icon button in top bar navigates to Search via More stack cross-tab"),
      body(""),

      heading("3.30 AgingChart Component (Session 11)", HeadingLevel.HEADING_2),
      bullet("AgingChart (src/components/AgingChart.tsx): reusable stacked horizontal aging bar with legend"),
      bullet("  Full-width proportional bar — each segment width = bucket amount / total amount", 1),
      bullet("  5 grayscale fills (light → dark) represent Current → Over-90-days severity", 1),
      bullet("  Legend grid below bar: colored dot + short label + formatted amount + % of total", 1),
      bullet("  Handles zero-total case gracefully (shows empty gray bar)", 1),
      bullet("AccountsPayableScreen: replaced 5 separate AgingBar rows with AgingChart component"),
      bullet("AccountsReceivableScreen: same replacement — removed AgingBar function and styles"),
      body(""),

      heading("3.27 Alerts & Notifications System (Session 10)", HeadingLevel.HEADING_2),
      bullet("OverdueContext (src/context/OverdueContext.tsx): apOverdue, arOverdue, lowStock, totalAlerts"),
      bullet("  AP/AR screens call setAPOverdue/setAROverdue; InventoryScreen calls setLowStock", 1),
      bullet("AlertsScreen (src/screens/alerts/AlertsScreen.tsx):"),
      bullet("  Aggregates all active alerts: overdue AP bills, overdue AR invoices, low-stock items", 1),
      bullet("  Loads from cache first for instant display, falls back to fresh API", 1),
      bullet("  Overdue bills/invoices sorted most-overdue-first with 'Xd overdue' badge", 1),
      bullet("  Low-stock items sorted by qty ascending (most critical first)", 1),
      bullet("  Tapping rows navigates cross-tab: bills/invoices → Finance; stock → Inventory", 1),
      bullet("  All-clear empty state when no alerts; pull-to-refresh", 1),
      bullet("Dashboard bell icon: top-bar button with badge showing totalAlerts (hidden when zero)"),
      bullet("Dashboard Alerts tile: quick-action tile with badge overlay"),
      bullet("Dashboard Finance Status panel: cards showing overdue bill/invoice counts; only visible when > 0"),
      bullet("FinanceMenuScreen: badge pills on AP + AR rows showing overdue counts from context"),
      bullet("MoreMenuScreen: Alerts banner at top with count breakdown and active border when alerts exist"),
      bullet("KPICard: shows Feather chevron-right in label row when onPress is provided"),
      body(""),

      heading("3.28 Dashboard KPI Navigation (Session 10)", HeadingLevel.HEADING_2),
      bullet("Revenue KPI card → navigates to Financial Reports (P&L tab)"),
      bullet("Expenses KPI card → navigates to Journal Entries"),
      bullet("Net Income KPI card → navigates to Financial Reports"),
      bullet("Receivables KPI card → navigates to Accounts Receivable"),
      bullet("Payables KPI card → navigates to Accounts Payable"),
      body(""),

      heading("3.24 API Client Retry Logic (Session 3)", HeadingLevel.HEADING_2),
      bullet("apiRequest() now retries 2 times on network errors and 5xx/429 HTTP status codes"),
      bullet("Exponential backoff delays: 500ms, 1000ms, 2000ms between attempts"),
      bullet("Helps recover from transient connectivity issues on mobile networks"),
      body(""),

      // 4. Roadmap
      heading("4. Feature Roadmap"),
      body("The following features are planned and will be built incrementally by the scheduled build agent:"),
      body(""),

      new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [
          tableRow(["Phase", "Screen", "Status", "API Endpoint"], { header: true, widths: [15, 25, 15, 45] }),
          tableRow(["Setup", "Login Screen", "Done", "/api/employees, /api/auth/switch"]),
          tableRow(["Setup", "Dashboard", "Done", "/api/dashboard"], { alt: true }),
          tableRow(["Phase 1", "Inventory", "Done", "/api/mobile/inventory"]),
          tableRow(["Phase 1", "Materials", "Done", "/api/mobile/materials"], { alt: true }),
          tableRow(["Phase 1", "Purchase Orders", "Done", "/api/mobile/purchase-orders"]),
          tableRow(["Phase 2", "Sales Orders", "Done", "/api/mobile/sales-orders"], { alt: true }),
          tableRow(["Phase 2", "GRN / Goods Receipt", "Done", "/api/mobile/purchase-orders?view=progress"]),
          tableRow(["Phase 3", "Accounts Payable", "Done", "/api/mobile/accounts-payable"], { alt: true }),
          tableRow(["Phase 3", "Accounts Receivable", "Done", "/api/mobile/accounts-receivable"]),
          tableRow(["Phase 3", "Journal Entries", "Done", "/api/mobile/journal-entries"], { alt: true }),
          tableRow(["Phase 4", "Trial Balance", "Done", "/api/mobile/trial-balance"]),
          tableRow(["Phase 4", "Financial Reports", "Done", "Computed from trial balance"], { alt: true }),
          tableRow(["Phase 5", "Business Partners", "Done", "/api/mobile/partners"]),
          tableRow(["Phase 5", "Companies", "Done", "/api/mobile/companies"], { alt: true }),
          tableRow(["Phase 6", "Navigation Wiring", "Done", "—"]),
          tableRow(["Phase 6", "Global Company Filter", "Done", "CompanyContext + CompanyPicker"], { alt: true }),
          tableRow(["Phase 6", "Polish & Empty States", "Done", "—"]),
          tableRow(["Session 4", "Back Buttons (all screens)", "Done", "—"], { alt: true }),
          tableRow(["Session 4", "Search (PO, SO, AP Bills, AP Vendors, AR Invoices, AR Customers)", "Done", "—"]),
          tableRow(["Session 4", "Date Range Filter + Presets (Journal Entries)", "Done", "/api/mobile/journal-entries?from=&to="], { alt: true }),
          tableRow(["Session 4", "GRN → PO Detail navigation", "Done", "—"]),
          tableRow(["Session 5", "Inventory Warehouses Tab", "Done", "/api/mobile/inventory?view=warehouses"], { alt: true }),
          tableRow(["Session 5", "Inventory Ledger Date Filter + Presets", "Done", "/api/mobile/inventory?view=ledger&from=&to="]),
          tableRow(["Session 5", "Low-Stock Filter on Stock Balances", "Done", "—"], { alt: true }),
          tableRow(["Session 5", "Trial Balance Export (Share API)", "Done", "—"]),
          tableRow(["Session 5", "Financial Reports Export (Share API)", "Done", "—"], { alt: true }),
          tableRow(["Session 5", "Journal Entries Export (Share API)", "Done", "—"]),
          tableRow(["Session 6", "Inventory Item Detail Screen", "Done", "/api/mobile/inventory?view=ledger&item_id="], { alt: true }),
          tableRow(["Session 6", "AP/AR Overdue Due-Date Alerts", "Done", "—"]),
          tableRow(["Session 6", "Offline Caching (AsyncStorage)", "Done", "—"], { alt: true }),
          tableRow(["Session 7", "Vendor Detail Screen (AP)", "Done", "/api/mobile/accounts-payable?view=bills (filtered client-side)"]),
          tableRow(["Session 7", "Customer Detail Screen (AR)", "Done", "/api/mobile/accounts-receivable?view=invoices (filtered client-side)"], { alt: true }),
          tableRow(["Session 7", "Offline Caching extended (AP, AR, Materials)", "Done", "—"]),
          tableRow(["Session 8", "Partner Detail Screen", "Done", "/api/mobile/purchase-orders + /api/mobile/sales-orders (filtered client-side)"], { alt: true }),
          tableRow(["Session 8", "Settings Screen (low-stock threshold, cache management)", "Done", "AsyncStorage"]),
          tableRow(["Session 8", "Offline Caching extended (PO list, SO list, Partners)", "Done", "—"], { alt: true }),
          tableRow(["Session 8", "Low-stock threshold wired to Settings (InventoryScreen)", "Done", "src/utils/settings.ts"]),
          tableRow(["Session 9", "Offline Caching for GRN / Companies / PO Detail / SO Detail", "Done", "—"], { alt: true }),
          tableRow(["Session 9", "Finance tab overdue badge (OverdueContext, AP+AR screens)", "Done", "—"]),
          tableRow(["Session 9", "Companies search/filter (name, code, active-only toggle)", "Done", "—"], { alt: true }),
          tableRow(["Session 10", "Alerts / Notifications Center Screen", "Done", "/api/mobile/accounts-payable + accounts-receivable + inventory"]),
          tableRow(["Session 10", "OverdueContext extended with lowStock + totalAlerts", "Done", "—"], { alt: true }),
          tableRow(["Session 10", "Dashboard: bell badge, Finance Status panel, all KPI cards tappable", "Done", "—"]),
          tableRow(["Session 10", "FinanceMenu: overdue badge pills on AP + AR rows", "Done", "—"], { alt: true }),
          tableRow(["Session 10", "MoreMenu: Alerts banner with count breakdown", "Done", "—"]),
          tableRow(["Session 10", "KPICard: chevron indicator when onPress provided", "Done", "—"], { alt: true }),
          tableRow(["Session 11", "Global Search Screen (POs, SOs, Stock, Materials, Partners)", "Done", "/api/mobile/* (cached)"]),
          tableRow(["Session 11", "AgingChart component — stacked bar replaces per-row bars in AP/AR", "Done", "—"], { alt: true }),
          tableRow(["Session 11", "Dashboard search icon button + MoreMenu search shortcut", "Done", "—"]),
          tableRow(["Session 12", "Skeleton loading system (7 components, 20+ screens migrated)", "Done", "—"], { alt: true }),
          tableRow(["Session 12", "Keyboard UX (keyboardShouldPersistTaps + keyboardDismissMode)", "Done", "—"]),
          tableRow(["Session 13", "Material Detail Screen — stock by warehouse + transactions + date filter", "Done", "/api/mobile/inventory"], { alt: true }),
          tableRow(["Session 13", "Dashboard Voucher Activity Chart — horizontal bar chart by type", "Done", "—"]),
          tableRow(["Session 13", "Search → MaterialDetail navigation (was navigating to list)", "Done", "—"], { alt: true }),
          tableRow(["Session 13", "Alerts low-stock items → MaterialDetail navigation", "Done", "—"]),
          tableRow(["Session 14", "Dashboard auto-refresh interval (configurable: Off/1/5/10/30 min)", "Done", "—"], { alt: true }),
          tableRow(["Session 14", "Dashboard 'last updated' relative timestamp in top bar", "Done", "—"]),
          tableRow(["Session 14", "Company selection persists across app restarts (AsyncStorage)", "Done", "—"], { alt: true }),
          tableRow(["Session 14", "Session timeout / security lock (auto-logout after background inactivity)", "Done", "AppState API"]),
          tableRow(["Session 14", "Journal Entries offline caching (per company+type, bypassed when date filter active)", "Done", "AsyncStorage"], { alt: true }),
          tableRow(["Session 15", "Trial Balance + Financial Reports offline caching (shared cache key, 24h TTL)", "Done", "AsyncStorage"]),
          tableRow(["Session 15", "Biometric lock (fingerprint / Face ID on app foreground)", "Done", "expo-local-authentication"], { alt: true }),
          tableRow(["Session 15", "Local push notifications — daily overdue reminders at 9 AM", "Done", "expo-notifications"]),
          tableRow(["Session 16", "Configurable notification time — chip picker (6AM–6PM)", "Done", "src/utils/settings.ts"], { alt: true }),
          tableRow(["Session 16", "Per-type notification toggles — AP overdue / AR overdue / Low-stock", "Done", "src/utils/settings.ts"]),
          tableRow(["Session 16", "Notification tap → Alerts screen navigation", "Done", "expo-notifications listener"], { alt: true }),
          tableRow(["Session 16", "Deep link navigation — poultryerp:// URL scheme", "Done", "expo-linking + linking.ts"]),
          tableRow(["Session 16", "PDF export — Trial Balance (styled HTML → PDF via expo-print)", "Done", "expo-print + expo-sharing"], { alt: true }),
          tableRow(["Session 16", "PDF export — P&L and Balance Sheet reports", "Done", "expo-print + expo-sharing"]),
          tableRow(["Session 16", "PDF export — Journal Entries with line items", "Done", "expo-print + expo-sharing"], { alt: true }),
          tableRow(["Session 17", "In-app notification inbox (history log, unread badge, clear all)", "Done", "src/utils/notificationLog.ts"]),
          tableRow(["Session 17", "Inbox screen with unread entry highlighting and breakdown chips", "Done", "src/screens/inbox/InboxScreen.tsx"], { alt: true }),
          tableRow(["Session 17", "More tab badge showing unread inbox count", "Done", "AppNavigator.tsx"]),
          tableRow(["Session 17", "Dashboard Inbox quick action tile + unread notification banner", "Done", "DashboardScreen.tsx"], { alt: true }),
          tableRow(["Session 17", "Batch PDF export — combined Trial Balance + P&L + Balance Sheet", "Done", "pdfExport.ts exportCombinedReportPDF"]),
          tableRow(["Session 17", "Bundle button in Trial Balance + Financial Reports screens", "Done", "expo-print + expo-sharing"], { alt: true }),
          tableRow(["Session 17", "Stock balances PDF export in Inventory screen", "Done", "exportStockBalancePDF"]),
          tableRow(["Session 18", "Bookmarks system — save POs, SOs, partners, materials for quick access", "Done", "src/utils/bookmarks.ts"], { alt: true }),
          tableRow(["Session 18", "BookmarkButton component — toggle on detail screen headers", "Done", "src/components/BookmarkButton.tsx"]),
          tableRow(["Session 18", "BookmarksScreen — grouped list with one-tap navigation to saved items", "Done", "src/screens/bookmarks/BookmarksScreen.tsx"], { alt: true }),
          tableRow(["Session 18", "Inbox swipe-to-delete — per-entry deletion via PanResponder gesture", "Done", "src/screens/inbox/InboxScreen.tsx"]),
          tableRow(["Session 18", "Multi-company KPI comparison — ranked metrics across all companies", "Done", "src/screens/comparison/ComparisonScreen.tsx"], { alt: true }),
          tableRow(["Session 19", "Bookmark count badge on Dashboard Bookmarks quick action tile", "Done", "DashboardScreen.tsx"]),
          tableRow(["Session 19", "PDF export — Bookmarks list (grouped by type with title/amount/date)", "Done", "pdfExport.ts exportBookmarksPDF"], { alt: true }),
          tableRow(["Session 19", "PDF export — Purchase Order detail (summary + receipt progress + line items)", "Done", "pdfExport.ts exportPODetailPDF"]),
          tableRow(["Session 19", "PDF export — Sales Order detail (summary + line items table)", "Done", "pdfExport.ts exportSODetailPDF"], { alt: true }),
          tableRow(["Session 19", "PDF export — Partner Detail (PO + SO history tables)", "Done", "pdfExport.ts exportPartnerDetailPDF"]),
          tableRow(["Session 19", "PDF export — Material Detail (stock by warehouse + ledger table)", "Done", "pdfExport.ts exportMaterialDetailPDF"], { alt: true }),
          tableRow(["Session 19", "PDF export — Vendor Detail (AP bills with overdue summary)", "Done", "pdfExport.ts exportVendorDetailPDF"]),
          tableRow(["Session 19", "PDF export — Customer Detail (AR invoices with overdue summary)", "Done", "pdfExport.ts exportCustomerDetailPDF"], { alt: true }),
          tableRow(["Session 20", "PDF export — Item Ledger (movement log with summary tiles + date range)", "Done", "pdfExport.ts exportItemLedgerPDF"]),
          tableRow(["Session 20", "PDF export — GRN Goods Receipt (progress summary + per-PO table with inline bars)", "Done", "pdfExport.ts exportGRNPDF"], { alt: true }),
          tableRow(["Session 20", "Cash Flow screen — upcoming AP/AR payments grouped by due date period", "Done", "src/screens/finance/CashFlowScreen.tsx"]),
          tableRow(["Session 20", "Dashboard Quick Actions expanded: Cash Flow, Partners, Reports tiles added (12 total)", "Done", "DashboardScreen.tsx"], { alt: true }),
        ],
      }),

      // 5. Directory Structure
      heading("5. Directory Structure"),
      body("src/", { bold: true }),
      bullet("api/"),
      bullet("client.ts — Fetch wrapper with JWT auth", 1),
      bullet("auth.ts — Login/logout API calls", 1),
      bullet("dashboard.ts — Dashboard data fetching", 1),
      bullet("inventory.ts — Stock balances, ledger, and warehouses (Warehouse interface + fetchWarehouses)", 1),
      bullet("materials.ts — Material master list and types", 1),
      bullet("purchaseOrders.ts — PO list and detail", 1),
      bullet("salesOrders.ts — SO list and detail", 1),
      bullet("accountsPayable.ts — AP summary, bills, vendors", 1),
      bullet("accountsReceivable.ts — AR summary, invoices, customers", 1),
      bullet("journalEntries.ts — Journal entry list with filters", 1),
      bullet("trialBalance.ts — Trial balance with company/date params", 1),
      bullet("partners.ts — Business partners list", 1),
      bullet("companies.ts — Company details", 1),
      bullet("src/components/ — Shared UI components (LoadingView, ErrorView, KPICard, SectionHeader, OfflineBanner)", 0),
      bullet("src/context/ — React contexts (AuthContext, CompanyContext)", 0),
      bullet("src/navigation/ — Navigation stack definitions", 0),
      bullet("AppNavigator.tsx — Bottom tabs with type-safe nested navigator params", 1),
      bullet("InventoryNavigator.tsx — Stack for Inventory tab: InventoryMain + ItemLedger (Session 6)", 1),
      bullet("FinanceNavigator.tsx — Stack for Finance tab screens", 1),
      bullet("MoreNavigator.tsx — Stack for More tab screens", 1),
      bullet("AuthNavigator.tsx — Stack for unauthenticated screens", 1),
      bullet("src/screens/ — Screen components by feature", 0),
      bullet("src/theme/ — Design tokens (colors, spacing, shadows)", 0),
      bullet("src/utils/ — Utility functions:", 0),
      bullet("currency.ts — formatCurrency, formatShortDate helpers", 1),
      bullet("cache.ts — getCached/setCached/clearCache; AsyncStorage offline cache with 24h TTL and versioning (Session 6)", 1),
      bullet("settings.ts — getLowStockThreshold/setLowStockThreshold/getAutoRefreshInterval/setAutoRefreshInterval/getSessionTimeout/setSessionTimeout/getBiometricEnabled/setBiometricEnabled (Sessions 8, 14–15)", 1),
      bullet("notifications.ts — requestNotificationPermissions, scheduleOverdueReminder (per-type + configurable hour), cancelOverdueReminder, getNotificationsEnabled/setNotificationsEnabled (Sessions 15–16)", 1),
      bullet("notificationLog.ts — logNotificationEvent, getInboxEntries, getUnreadCount, markAllRead, deleteInboxEntry, clearInbox; AsyncStorage inbox log with max 50 entries (Sessions 17–18)", 1),
      bullet("pdfExport.ts — exportTrialBalancePDF, exportPLPDF, exportBSPDF, exportJournalEntriesPDF, exportCombinedReportPDF, exportStockBalancePDF, exportMaterialDetailPDF, exportPODetailPDF, exportSODetailPDF, exportPartnerDetailPDF, exportVendorDetailPDF, exportCustomerDetailPDF, exportBookmarksPDF, exportItemLedgerPDF, exportGRNPDF via expo-print + expo-sharing (Sessions 16–20)", 1),
      bullet("bookmarks.ts — addBookmark, removeBookmark, isBookmarked, getBookmarks, clearBookmarks; AsyncStorage-backed per-type bookmark registry (max 100 entries) (Session 18)", 1),
      bullet("src/hooks/ — Custom React hooks:", 0),
      bullet("useSessionTimeout.ts — AppState-based session lock hook; triggers onTimeout when background exceeds configured limit (Session 14)", 1),
      bullet("src/screens/inbox/ — Inbox screen (notification history, swipe-to-delete, clear all) (Sessions 17–18)", 0),
      bullet("src/screens/bookmarks/ — BookmarksScreen (saved items grouped by type, tap to navigate, per-item delete) (Session 18)", 0),
      bullet("src/screens/comparison/ — ComparisonScreen (multi-company KPI ranking with proportional bars, pull-to-refresh) (Session 18)", 0),
      bullet("src/components/BookmarkButton.tsx — Toggle bookmark icon button for detail screen headers (Session 18)", 0),
      bullet("src/navigation/linking.ts — React Navigation LinkingOptions mapping poultryerp:// URLs to screen names (Sessions 16–20)", 0),
      bullet("src/screens/finance/CashFlowScreen.tsx — Cash Flow screen: upcoming AP bills + AR invoices grouped by due date period (Session 20)", 0),

      // 6. Setup
      heading("6. Development Setup"),
      body("Prerequisites:", { bold: true }),
      bullet("Node.js 18+"),
      bullet("Expo CLI (npx expo)"),
      bullet("Expo Go app on iOS/Android device"),
      bullet("Next.js web app running (for backend API)"),
      body(""),
      body("Steps:", { bold: true }),
      bullet("1. Clone the repo: git clone github.com/haseebahmad24/Poultry-ERP-Mobile"),
      bullet("2. Install dependencies: npm install --legacy-peer-deps"),
      bullet("3. Create .env file with EXPO_PUBLIC_API_URL=http://<your-lan-ip>:3000"),
      bullet("4. Start the Next.js web app (backend): cd <web-repo> && npm run dev"),
      bullet("5. Start Expo: npm run start"),
      bullet("6. Scan QR code with Expo Go on your phone"),
      body(""),
      body("Both devices must be on the same local network.", { italics: true, color: GRAY }),

      // 7. Changelog
      heading("7. Changelog"),
      heading("Session 2 — 2026-05-16", HeadingLevel.HEADING_2),
      bullet("Added API service modules: inventory, materials, purchase orders"),
      bullet("Built InventoryScreen with Stock Balances and Stock Ledger tabs"),
      bullet("Built MaterialsScreen with search, status filter, and type filter pills"),
      bullet("Built PurchaseOrdersScreen with status tabs, live counts, and progress bars"),
      bullet("Built PODetailScreen with header info, receiving progress, and line items"),
      bullet("Created AppStack navigator — wraps bottom tabs + all new feature screens"),
      bullet("Wired Dashboard Quick Actions: Inventory, Materials, Purchase Order navigate correctly"),
      bullet("Fixed: InventoryScreen hides back button when accessed as bottom tab"),
      body(""),
      heading("Session 1 — 2026-05-12", HeadingLevel.HEADING_2),
      bullet("Project scaffolded with Expo 51, TypeScript, React Navigation"),
      bullet("Design system created matching web app colors"),
      bullet("API client with JWT auth via Secure Store"),
      bullet("Login screen with employee selector"),
      bullet("Dashboard with KPIs, working capital, quick actions, recent activity"),
      bullet("Bottom tab navigation (Dashboard, Inventory, Finance, More)"),
      body(""),

      heading("Session 2 — 2026-05-15", HeadingLevel.HEADING_2),
      bullet("Phase 1: Inventory screen (stock balances + ledger tab view, search)"),
      bullet("Phase 1: Materials screen (searchable list, type filter chips, status badges)"),
      bullet("Phase 1: Purchase Orders screen (All/Open/In Progress tabs, PO detail with progress bar)"),
      bullet("Phase 2: Sales Orders screen (All/Open/Approved/Closed tabs, SO detail with line items)"),
      bullet("Phase 2: GRN screen (receipt progress per PO, overall summary card)"),
      bullet("Phase 3: Accounts Payable screen (summary/aging, bills, vendors tabs)"),
      bullet("Phase 3: Accounts Receivable screen (summary/aging, invoices, customers tabs)"),
      bullet("Phase 3: Journal Entries screen (type filter chips, expandable cards with journal lines)"),
      bullet("Phase 4: Trial Balance screen (company selector, date input, hierarchical account table)"),
      bullet("Phase 4: Financial Reports screen (P&L and Balance Sheet tabs computed from trial balance)"),
      bullet("Phase 5: Business Partners screen (role filter, customer/vendor badges)"),
      bullet("Phase 5: Companies screen (company cards with fiscal year, status, contact info)"),
      bullet("Phase 6: FinanceNavigator and MoreNavigator stack navigators wired up"),
      bullet("Phase 6: Dashboard Quick Action tiles wired to real screens via tab navigation"),
      bullet("Phase 6: CompanyContext and CompanyPicker for global company filtering"),
      bullet("Phase 6: Inventory, AP, AR screens use global company filter"),
      body(""),
      heading("Session 3 — 2026-05-18", HeadingLevel.HEADING_2),
      bullet("Global company filter extended to all screens: Dashboard, Materials, Journal Entries, Partners, Sales Orders"),
      bullet("TrialBalance and FinancialReports now read companies from CompanyContext (no redundant API calls)"),
      bullet("CompanyContext fixed to reload after login instead of failing silently on app start"),
      bullet("API client: added exponential-backoff retry (2 attempts, 500/1000ms) for network errors and 5xx/429"),
      bullet("MoreMenu Finance section: removed disabled items, now navigates directly into Finance tab screens"),
      bullet("AppStack: removed dead duplicate routes (Inventory, Materials, POs) — all nav through tab stacks"),
      bullet("Fixed Inventory tab icon (was using wrong key InventoryTab instead of Inventory)"),
      bullet("PurchaseOrder type: added received/receipt_pct fields for progress view endpoint"),
      body(""),
      heading("Session 4 — 2026-05-19", HeadingLevel.HEADING_2),
      bullet("Journal Entries: added date range filter (from/to inputs) with server-side filtering via API params"),
      bullet("Journal Entries: added quick date presets — Today, This Week, This Month, Last Month"),
      bullet("Accounts Payable: added search bars in Bills tab (by number/vendor/status) and Vendors tab (by name)"),
      bullet("Accounts Receivable: added search bars in Invoices tab (by number/customer/status) and Customers tab (by name)"),
      bullet("Purchase Orders: added search bar (by PO number, vendor, status)"),
      bullet("Sales Orders: added search bar (by SO number, customer, status)"),
      bullet("GRN screen: made PO cards tappable — tap navigates to PurchaseOrderDetail screen"),
      bullet("Back buttons: added BackButton component to all non-root stack screens (11 screens total)"),
      bullet("Back button header style: fixed AP, AR, Financial Reports headers to use flexDirection row"),
      body(""),
      heading("Session 5 — 2026-05-19", HeadingLevel.HEADING_2),
      bullet("Inventory: added 3rd Warehouses tab — card list showing name, code, type, address, active/inactive status"),
      bullet("Inventory: added fetchWarehouses() API function using ?view=warehouses endpoint"),
      bullet("Inventory: added date range filter panel on Stock Ledger tab with From/To inputs"),
      bullet("Inventory: date filter presets on Ledger: Today, This Week, This Month, Last Month"),
      bullet("Inventory: added Low Stock / Out of Stock filter chips on Stock Balances tab with live counts"),
      bullet("Inventory: low stock threshold = qty < 100; out of stock = qty <= 0; counts shown in chip labels"),
      bullet("Trial Balance: added Export button — shares formatted columnar text (Account | Debit | Credit) via Share API"),
      bullet("Trial Balance: export includes company name, as-of date, totals row, balanced/out-of-balance status"),
      bullet("Financial Reports: added Export button — shares P&L or Balance Sheet as tab-delimited text"),
      bullet("Journal Entries: added Export button — shares filtered JE list with voucher lines as formatted text"),
      body(""),
      heading("Session 6 — 2026-05-19", HeadingLevel.HEADING_2),
      bullet("Inventory: stock balance cards are now tappable — tap navigates to ItemLedgerScreen for that item"),
      bullet("Inventory: created ItemLedgerScreen with summary bar (total in/out/balance), date filter + presets, pull-to-refresh"),
      bullet("Inventory: created InventoryNavigator (stack) wrapping InventoryMain + ItemLedger screens"),
      bullet("Accounts Payable: overdue bills sorted to top, tab badge shows overdue count, red left border + warning banner"),
      bullet("Accounts Receivable: overdue invoices sorted to top, tab badge shows overdue count, red left border + warning banner"),
      bullet("AP/AR: daysOverdue() helper computes calendar days past due_date (0 for paid or current)"),
      bullet("AP/AR: SectionHeader meta shows 'N records · M overdue' when overdue items exist"),
      bullet("Offline caching: installed @react-native-async-storage/async-storage"),
      bullet("Offline caching: created src/utils/cache.ts with getCached/setCached (24h TTL, versioned)"),
      bullet("Offline caching: created src/components/OfflineBanner.tsx — amber banner for stale data"),
      bullet("Offline caching: DashboardScreen shows cached KPIs instantly, fetches fresh in background"),
      bullet("Offline caching: InventoryScreen caches stock balances per company, populates UI from cache immediately"),
      body(""),
      heading("Session 8 — 2026-05-20", HeadingLevel.HEADING_2),
      bullet("Created PartnerDetailScreen (src/screens/partners/PartnerDetailScreen.tsx)"),
      bullet("  — Tap any partner card in PartnersScreen to view their PO and/or SO history", 1),
      bullet("  — Summary tiles: Total PO value + count (vendors) / Total SO value + count (customers)", 1),
      bullet("  — Dual-role tab bar (POs | SOs) shown when partner is both vendor and customer", 1),
      bullet("  — PO cards navigate to PurchaseOrderDetail; SO cards navigate to SalesOrderDetail", 1),
      bullet("Created SettingsScreen (src/screens/settings/SettingsScreen.tsx)"),
      bullet("  — Low-stock threshold input with save/confirmation feedback", 1),
      bullet("  — Clear cached data action with destructive confirmation alert", 1),
      bullet("  — About section with app name and version", 1),
      bullet("Created src/utils/settings.ts — getLowStockThreshold / setLowStockThreshold via AsyncStorage"),
      bullet("InventoryScreen: replaced hardcoded LOW_STOCK_THRESHOLD=100 with getLowStockThreshold() from settings"),
      bullet("PartnersScreen: made partner cards tappable (→ PartnerDetail); added offline caching per company"),
      bullet("PurchaseOrdersScreen: added offline caching per tab (all/open/progress) with OfflineBanner"),
      bullet("SalesOrdersScreen: added offline caching per tab+company combo with OfflineBanner"),
      bullet("MoreNavigator: added PartnerDetail + Settings routes"),
      bullet("MoreMenuScreen: added Settings link under Admin section"),
      body(""),
      heading("Session 7 — 2026-05-20", HeadingLevel.HEADING_2),
      bullet("Created VendorDetailScreen (src/screens/finance/VendorDetailScreen.tsx)"),
      bullet("  — Tap any vendor card or top-vendor row in AP screen to view their full bill history", 1),
      bullet("  — Summary tiles: Outstanding, Overdue (highlighted), Total Billed, Bill count", 1),
      bullet("  — Bills sorted overdue-first, each with overdue-days alert banner", 1),
      bullet("  — Search by bill number or status, pull-to-refresh", 1),
      bullet("Created CustomerDetailScreen (src/screens/finance/CustomerDetailScreen.tsx)"),
      bullet("  — Same pattern as VendorDetail but for AR customers → invoice history", 1),
      bullet("  — Tap any customer card or top-customer row in AR screen", 1),
      bullet("AccountsPayableScreen: VendorCard and summary mini-list now tappable (chevron-right affordance)"),
      bullet("AccountsReceivableScreen: CustomerCard and summary mini-list now tappable (chevron-right affordance)"),
      bullet("FinanceNavigator: added VendorDetail + CustomerDetail routes with typed params"),
      bullet("Offline caching extended to AccountsPayableScreen (summary/bills/vendors per company)"),
      bullet("Offline caching extended to AccountsReceivableScreen (summary/invoices/customers per company)"),
      bullet("Offline caching extended to MaterialsScreen (materials + types per company+type combo)"),
      body(""),
      heading("Session 9 — 2026-05-21", HeadingLevel.HEADING_2),
      bullet("Offline caching extended to GRNScreen (per company, 24h TTL)"),
      bullet("Offline caching extended to CompaniesScreen"),
      bullet("Offline caching extended to PODetailScreen and PurchaseOrderDetailScreen (per PO ID)"),
      bullet("Offline caching extended to SalesOrderDetailScreen (per SO ID)"),
      bullet("Created OverdueContext (src/context/OverdueContext.tsx) with apOverdue / arOverdue / totalOverdue"),
      bullet("AccountsPayableScreen: calls setAPOverdue(count) after loading bills"),
      bullet("AccountsReceivableScreen: calls setAROverdue(count) after loading invoices"),
      bullet("AppNavigator: Finance tab badge displays totalOverdue count from OverdueContext"),
      bullet("CompaniesScreen: added real-time search by name/code and active-only toggle chip"),
      body(""),
      heading("Session 10 — 2026-05-21", HeadingLevel.HEADING_2),
      bullet("Created AlertsScreen (src/screens/alerts/AlertsScreen.tsx)"),
      bullet("  — Aggregates overdue AP bills, overdue AR invoices, low-stock items", 1),
      bullet("  — Cache-first data loading; cross-tab navigation on row tap", 1),
      bullet("  — All-clear empty state; pull-to-refresh; updates OverdueContext on load", 1),
      bullet("Extended OverdueContext: added lowStock, setLowStock, totalAlerts fields"),
      bullet("InventoryScreen: publishes low-stock count to OverdueContext via useEffect"),
      bullet("MoreNavigator: added Alerts route"),
      bullet("MoreMenuScreen: Alerts banner at top with count breakdown; active border when alerts exist"),
      bullet("Dashboard: bell icon with totalAlerts badge, Alerts quick-action tile with badge, Finance Status panel"),
      bullet("Dashboard KPI cards: Revenue, Expenses, Net Income, Receivables, Payables are all now tappable"),
      bullet("FinanceMenuScreen: AP and AR rows show overdue count pill badges from OverdueContext"),
      bullet("KPICard component: chevron-right indicator in label row when onPress prop is provided"),
      body(""),
      heading("Session 11 — 2026-05-22", HeadingLevel.HEADING_2),
      bullet("Created GlobalSearch screen (src/screens/search/SearchScreen.tsx)"),
      bullet("  — Cache-first data loading of POs, SOs, Materials, Partners, Stock Balances", 1),
      bullet("  — Instant client-side filtering with minimum 2-char threshold", 1),
      bullet("  — Results grouped by type; tapping navigates to respective detail screens", 1),
      bullet("  — Cross-tab navigation for stock results → Inventory > ItemLedger", 1),
      bullet("Added Search route to MoreNavigator"),
      bullet("MoreMenuScreen: search shortcut bar taps into SearchScreen"),
      bullet("DashboardScreen: search icon (Feather 'search') added to top bar header"),
      bullet("Created AgingChart component (src/components/AgingChart.tsx)"),
      bullet("  — Stacked horizontal bar: proportional segment widths per aging bucket", 1),
      bullet("  — Legend grid with colored dot, short label, amount, and percentage", 1),
      bullet("AccountsPayableScreen: replaced 5 AgingBar rows with AgingChart; removed AgingBar fn + styles"),
      bullet("AccountsReceivableScreen: same AgingChart migration"),
      body(""),
      heading("Session 20 — 2026-05-26", HeadingLevel.HEADING_2),
      bullet("PDF export — Item Ledger (src/screens/inventory/ItemLedgerScreen.tsx, pdfExport.ts)"),
      bullet("  exportItemLedgerPDF(): item name + code in header, date range when filter active, 4-tile summary (total in/out/balance/count)", 1),
      bullet("  Full movement log table: Type | Voucher # | Date | Warehouse | In | Out | Balance | Unit", 1),
      bullet("  ItemLedgerScreen: Feather file-text PDF button in header; visible only when entries are loaded", 1),
      bullet("PDF export — GRN Goods Receipt (src/screens/grn/GRNScreen.tsx, pdfExport.ts)"),
      bullet("  exportGRNPDF(): 4-tile summary (PO count/complete count/overall pct/value received)", 1),
      bullet("  Per-PO table with inline CSS progress bar + expandable line item sub-rows (item name + received/ordered/pct)", 1),
      bullet("  GRNScreen: CompanyContext added; Feather file-text PDF button in header; visible when orders loaded", 1),
      bullet("  GRNScreen: header alignItems baseline → center to accommodate the icon button", 1),
      bullet("Cash Flow screen (src/screens/finance/CashFlowScreen.tsx)"),
      bullet("  Fetches outstanding AP bills + AR invoices in parallel; filters to only items with outstanding > 0", 1),
      bullet("  Periods: Overdue | This Week | Next Week | 2-3 Weeks | 3-4 Weeks | 30+ Days | No Due Date", 1),
      bullet("  Summary tiles: Total Payable / Total Receivable; Net Cash Position card (darker border when negative)", 1),
      bullet("  Per-period: TO PAY group (bills) and TO COLLECT group (invoices), each with party / ref / amount / due date rows", 1),
      bullet("  Period Net row per section; overdue groups get bold border treatment", 1),
      bullet("  24h offline cache per company; CompanySelector; OfflineBanner; ErrorView; ListScreenSkeleton; pull-to-refresh", 1),
      bullet("  Wired into FinanceNavigator (CashFlow route + headerShown: false), FinanceMenuScreen (trending-up icon)", 1),
      bullet("  poultryerp://finance/cash-flow deep link added to linking.ts", 1),
      bullet("Dashboard Quick Actions expanded from 9 to 12 tiles (4 complete rows of 3)"),
      bullet("  New tiles: Cash Flow → Finance > CashFlow, Partners → More > Partners, Reports → Finance > FinancialReports", 1),
      body(""),
      heading("Session 19 — 2026-05-25", HeadingLevel.HEADING_2),
      bullet("Bookmark count badge on Dashboard Bookmarks quick action tile"),
      bullet("  DashboardScreen: bookmarkCount state loaded from getBookmarks().length on every useFocusEffect", 1),
      bullet("  Badge wired into quick tile renderer alongside existing Alerts and Inbox badges", 1),
      bullet("  Badge shows count of saved bookmarks; disappears when count is 0", 1),
      bullet("PDF export — BookmarksScreen"),
      bullet("  exportBookmarksPDF(): summary grid by type, then per-type tables (title / details / amount / saved date)", 1),
      bullet("  Feather file-text button added to BookmarksScreen header alongside Clear all; only visible when list non-empty", 1),
      bullet("PDF export — PurchaseOrderDetailScreen"),
      bullet("  exportPODetailPDF(po): PO summary tiles (status/amount/dates) + receipt progress bar + full line items table", 1),
      bullet("  Columns: item / ordered / received / pending / unit / rate / amount; totals row; filename from po_number", 1),
      bullet("  Feather file-text button in PO detail header between BackButton and BookmarkButton", 1),
      bullet("PDF export — SalesOrderDetailScreen"),
      bullet("  exportSODetailPDF(so): SO summary tiles + line items table (qty/unit/rate/amount); totals row; filename from so_number", 1),
      bullet("  Feather file-text button in SO detail header between BackButton and BookmarkButton", 1),
      bullet("PDF export — PartnerDetailScreen"),
      bullet("  exportPartnerDetailPDF(): PO + SO summary tiles, separate PO/SO tables with date/status/amount, totals rows", 1),
      bullet("  Feather file-text button in PartnerDetail header; filename from partnerName", 1),
      bullet("PDF export — MaterialDetailScreen"),
      bullet("  exportMaterialDetailPDF(): 4-tile summary, stock-by-warehouse table, ledger table (date/type/voucher/wh/in/out/balance)", 1),
      bullet("  Feather file-text button in MaterialDetail header; receives live stock+ledger state at press time", 1),
      bullet("PDF export — VendorDetailScreen"),
      bullet("  exportVendorDetailPDF(): 4-tile summary (outstanding/overdue/total/count), bills table with amount/paid/outstanding", 1),
      bullet("  Button only visible when bills.length > 0; filename from vendorName", 1),
      bullet("PDF export — CustomerDetailScreen"),
      bullet("  exportCustomerDetailPDF(): same pattern as Vendor but for AR invoices", 1),
      bullet("  Button only visible when invoices.length > 0; filename from customerName", 1),
      body(""),
      heading("Session 18 — 2026-05-25", HeadingLevel.HEADING_2),
      bullet("Bookmarks system (src/utils/bookmarks.ts + src/screens/bookmarks/BookmarksScreen.tsx)"),
      bullet("  bookmarks.ts: addBookmark, removeBookmark, isBookmarked, getBookmarks, clearBookmarks — AsyncStorage-backed, max 100, sorted by recency", 1),
      bullet("  Bookmark types: po | so | partner | material — each stores entityId, title, subtitle, meta, navParams for navigation", 1),
      bullet("  BookmarkButton component: toggle star/bookmark icon; reads initial state on mount; persists on press; accepts optional color prop for dark headers", 1),
      bullet("  BookmarksScreen: FlatList grouped by type (POs, SOs, Partners, Materials); tap navigates to detail screen; X removes individual entry; Clear all with confirmation; empty state", 1),
      bullet("  MoreNavigator: Bookmarks route added; MoreMenuScreen ADMIN section: Bookmarks item; linking.ts: poultryerp://bookmarks", 1),
      bullet("  BookmarkButton wired into PurchaseOrderDetailScreen, SalesOrderDetailScreen, PartnerDetailScreen, MaterialDetailScreen headers", 1),
      bullet("  DashboardScreen: Bookmarks added as 9th quick action tile", 1),
      bullet("Inbox swipe-to-delete (src/screens/inbox/InboxScreen.tsx)"),
      bullet("  notificationLog.ts: new deleteInboxEntry(id) function", 1),
      bullet("  SwipeableEntryRow component using PanResponder + Animated.Value", 1),
      bullet("  Swipe left > 80px threshold snaps open a 72px dark delete action button", 1),
      bullet("  Tap delete button: animates card off-screen then removes entry from state + AsyncStorage", 1),
      bullet("  Snap-back spring animation when swipe < threshold; header subtitle shows 'Swipe left to delete' when entries present", 1),
      bullet("Multi-company KPI comparison (src/screens/comparison/ComparisonScreen.tsx)"),
      bullet("  Fetches KPIs for all companies in parallel via existing fetchDashboardData(companyId)", 1),
      bullet("  Company status chips row: dot (loaded) / spinner (loading) / alert-circle (failed) per company", 1),
      bullet("  Summary tiles: total companies / loaded / loading / failed counts", 1),
      bullet("  9 ranked metric sections: Net Income, Revenue, Expenses, Cash Balance, AR, AP, Vouchers MTD, Working Capital", 1),
      bullet("  Each section: companies ranked by value; proportional horizontal bars (top = full-weight bar + bold value); negative values use muted bar", 1),
      bullet("  Pull-to-refresh reloads all companies in parallel; MoreNavigator + MoreMenuScreen ADMIN + poultryerp://comparison deep link", 1),
      body(""),
      heading("Session 17 — 2026-05-25", HeadingLevel.HEADING_2),
      bullet("In-app notification inbox (src/utils/notificationLog.ts + src/screens/inbox/InboxScreen.tsx)"),
      bullet("  notificationLog.ts: logNotificationEvent, getInboxEntries, getUnreadCount, markAllRead, clearInbox (AsyncStorage, max 50 entries)", 1),
      bullet("  notifications.ts: scheduleOverdueReminder now calls logNotificationEvent on every successful schedule", 1),
      bullet("  InboxScreen: FlatList of notification history; bold border + dot for unread; breakdown chips (AP/AR/Stock); clear all with confirmation; marks all read on open", 1),
      bullet("  MoreNavigator: Inbox route added; linking.ts: poultryerp://inbox deep link", 1),
      bullet("  MoreMenuScreen: split alerts banner into side-by-side Alerts + Inbox banners; Inbox shows unread count", 1),
      bullet("  AppNavigator: More tab badge shows inboxUnread; refreshed on mount + foreground transitions", 1),
      bullet("Dashboard inbox integration"),
      bullet("  Inbox added as 8th Quick Action tile (Feather inbox icon) with unread badge", 1),
      bullet("  Inbox unread banner shown between Finance Status and Quick Actions when unread > 0", 1),
      bullet("  inboxUnread state loaded via getUnreadCount() on every Dashboard focus event", 1),
      bullet("Batch PDF export — exportCombinedReportPDF()"),
      bullet("  Combined HTML document: cover page with TOC + Trial Balance + P&L + Balance Sheet sections", 1),
      bullet("  Page-break dividers between sections with section numbers; COMBINED_EXTRA_CSS for print layout", 1),
      bullet("  classifyRow() helper embedded in pdfExport.ts to classify accounts into report categories", 1),
      bullet("  Bundle button (Feather layers) added to TrialBalanceScreen header; uses all rows (unfiltered)", 1),
      bullet("  Bundle button added to FinancialReportsScreen header alongside existing PDF + Share buttons", 1),
      bullet("Stock balances PDF export in Inventory screen"),
      bullet("  exportStockBalancePDF(): item/warehouse/qty/unit table with summary grid (items + total qty)", 1),
      bullet("  PDF button shown in Inventory header on Stock tab when data is loaded; respects current filter", 1),
      body(""),
      heading("Session 16 — 2026-05-24", HeadingLevel.HEADING_2),
      bullet("Notification improvements — configurable time and per-type toggles"),
      bullet("  settings.ts: 4 new settings keys — notificationHour, notifyApOverdue, notifyArOverdue, notifyLowStock", 1),
      bullet("  notifications.ts: scheduleOverdueReminder now reads per-type settings — filters disabled types from notification body; uses configured hour instead of hardcoded 9 AM", 1),
      bullet("  SettingsScreen: new NOTIFICATIONS section with master toggle, 8-option time picker, and 3 per-type Switches (AP/AR/Stock)", 1),
      bullet("  Per-type controls are only visible when the master Overdue reminders toggle is on", 1),
      bullet("  AppNavigator: addNotificationResponseReceivedListener — tapping the daily reminder navigates to Alerts screen", 1),
      bullet("Deep link navigation (poultryerp:// URL scheme)"),
      bullet("  app.json: added scheme 'poultryerp'", 1),
      bullet("  expo-linking installed", 1),
      bullet("  src/navigation/linking.ts: LinkingOptions mapping 17 URL paths to screen names across all tab navigators", 1),
      bullet("  RootNavigator: NavigationContainer now receives linking config when user is authenticated", 1),
      bullet("PDF export for financial reports"),
      bullet("  expo-print + expo-sharing installed", 1),
      bullet("  src/utils/pdfExport.ts: 4 export functions — exportTrialBalancePDF, exportPLPDF, exportBSPDF, exportJournalEntriesPDF", 1),
      bullet("  All use shared BASE_CSS (monochrome print stylesheet) + printAndShare helper (PDF → OS share sheet)", 1),
      bullet("  TrialBalanceScreen: PDF button (file-text) added alongside existing Share text button", 1),
      bullet("  FinancialReportsScreen: PDF button dispatches to P&L or BS based on active tab", 1),
      bullet("  JournalEntriesScreen: PDF button added — export includes summary grid + full entry table with line items", 1),
      body(""),
      heading("Session 15 — 2026-05-24", HeadingLevel.HEADING_2),
      bullet("Trial Balance + Financial Reports offline caching"),
      bullet("  Both screens now use getCached/setCached pattern — serve data instantly on mount, refresh in background", 1),
      bullet("  Cache key: trial-balance:<companyId>:<asOf> — shared between both screens (same API endpoint)", 1),
      bullet("  OfflineBanner shown when stale cached data is served after a failed refresh", 1),
      bullet("  Error guard: ErrorView only shown when no cached data is available", 1),
      bullet("Biometric lock feature (expo-local-authentication)"),
      bullet("  BiometricLockOverlay component: full-screen overlay, auto-triggers authenticateAsync() on mount", 1),
      bullet("  AppNavigator: AppState listener triggers biometric lock on every background→foreground transition when enabled", 1),
      bullet("  SettingsScreen: Biometric lock Switch in SECURITY section (hidden when biometric hardware unavailable)", 1),
      bullet("  Enable flow: requires one successful auth first to prevent accidental lockout", 1),
      bullet("  settings.ts: added getBiometricEnabled / setBiometricEnabled", 1),
      bullet("Local push notifications for overdue items (expo-notifications)"),
      bullet("  notifications.ts: scheduleOverdueReminder schedules a daily notification at 9 AM when alerts exist", 1),
      bullet("  Notification body includes: 'N overdue bills · N overdue invoices · N low-stock items'", 1),
      bullet("  AppNavigator: reschedules notification via useEffect on [apOverdue, arOverdue, lowStock]", 1),
      bullet("  SettingsScreen: 'Overdue reminders' Switch in SECURITY section; OS permission requested on enable", 1),
      body(""),
      heading("Session 14 — 2026-05-24", HeadingLevel.HEADING_2),
      bullet("Dashboard auto-refresh interval setting (Off/1/5/10/30 min); persists in AsyncStorage"),
      bullet("  useFocusEffect re-reads interval on every Dashboard focus, picks up Settings changes immediately", 1),
      bullet("  Silent load(isSilent=true) — auto-refresh runs in background without showing RefreshControl", 1),
      bullet("  setInterval wires to load(); cleared on unmount or interval change", 1),
      bullet("Dashboard 'last updated' relative timestamp shown in top-bar subGreeting"),
      bullet("  Tracks successful fetch timestamp; 60s tick timer keeps label fresh without API calls", 1),
      bullet("  'Auto ↻Xm' indicator shown when auto-refresh is active", 1),
      bullet("Company selection persisted to AsyncStorage (setting:selectedCompanyId)"),
      bullet("  CompanyContext.setSelectedCompany wraps setSelectedCompanyState + AsyncStorage.setItem", 1),
      bullet("  On restart: load() reads saved ID alongside companies; restores previous selection or falls back to first", 1),
      bullet("Session timeout / security lock feature"),
      bullet("  src/hooks/useSessionTimeout.ts: AppState-based hook; no extra native packages required", 1),
      bullet("  Records backgroundedAt on background; re-reads setting on each background event", 1),
      bullet("  On foreground: if elapsed >= timeout, calls onTimeout() (wired to logout() in AppNavigator)", 1),
      bullet("  SettingsScreen: new SECURITY section — chip picker for Off/5m/15m/30m/1hr", 1),
      bullet("Journal Entries offline caching (24h TTL, per company+type combo; bypassed when date filter active)"),
      bullet("  Serves cache instantly on mount; refreshes in background; OfflineBanner on stale+error", 1),
      bullet("Removed unused AsyncStorage import from SettingsScreen"),
      body(""),
      heading("Session 13 — 2026-05-23", HeadingLevel.HEADING_2),
      bullet("Material Detail Screen: full drill-down from material list, search, and alerts"),
      bullet("  Header: name + code badge + meta chips (type/category/unit/status) + optional description bar", 1),
      bullet("  Summary tiles 2×2: Total Stock / Warehouse Count / Total In / Total Out", 1),
      bullet("  Stock by Warehouse: per-warehouse cards with qty, low-stock / out-of-stock indicators", 1),
      bullet("  Transactions section: up to 50 ledger entries with voucher badges, qty deltas, running balance", 1),
      bullet("  DateRangeBar on transactions: Today/This Week/This Month/Last Month/Custom — re-fetches with date params", 1),
      bullet("  24h offline cache; DetailSkeleton; ErrorView; pull-to-refresh", 1),
      bullet("Dashboard Voucher Activity Chart (VoucherActivityChart component):"),
      bullet("  Horizontal proportional bars: top-6 voucher types sorted by count", 1),
      bullet("  Each row: type label + bar track + count badge + formatted amount", 1),
      bullet("  fetchDashboardData now returns voucherTypeStats[] from monthly JE aggregation", 1),
      bullet("  'Activity by Type' section added to Dashboard between Quick Actions and Recent Activity", 1),
      bullet("Search → MaterialDetail: tapping a material in Global Search now opens MaterialDetail directly"),
      bullet("  materialMeta added to SearchResult; materialToResult populates it; navigate path fixed", 1),
      bullet("Alerts → MaterialDetail: low-stock items now navigate to MaterialDetail when item_id is available"),
      body(""),
      heading("Session 12 — 2026-05-23", HeadingLevel.HEADING_2),
      bullet("Animated Skeleton Loading System — replaced all full-screen spinners with shimmer skeletons"),
      bullet("  SkeletonBox: animated pulse (opacity 0.4→1.0→0.4 loop, 700ms per leg, useNativeDriver)", 1),
      bullet("  SkeletonListItem: card skeleton — left column (title+subtitle+meta), optional right badge column", 1),
      bullet("  SkeletonKPICard: matches KPI card proportions (label + number + sub-label rows)", 1),
      bullet("  DashboardSkeleton: standalone full-page — top bar + 2×2 KPI grid + 6 quick tiles + 4 voucher rows", 1),
      bullet("  ListScreenSkeleton: inline — optional search bar + optional tab bar + N list items", 1),
      bullet("  FinanceSummarySkeleton: inline — 2×2 summary tiles + aging bar + tab bar + N rows", 1),
      bullet("  DetailSkeleton: inline — configurable summary tiles (2-col rows) + section label + N rows", 1),
      bullet("Migrated 20+ screens from ActivityIndicator spinner to skeleton loading:"),
      bullet("  DashboardScreen: full-page DashboardSkeleton (entire screen chrome, header included)", 1),
      bullet("  PurchaseOrdersScreen: header stays visible; skeleton body replaces search+tabs+list", 1),
      bullet("  SalesOrdersScreen, MaterialsScreen, PartnersScreen, CompaniesScreen: same inline pattern", 1),
      bullet("  InventoryScreen: header + tab bar stay; skeleton replaces content body", 1),
      bullet("  AccountsPayableScreen + AccountsReceivableScreen: FinanceSummarySkeleton in body", 1),
      bullet("  JournalEntriesScreen: header stays; skeleton replaces date filter+search+list", 1),
      bullet("  AlertsScreen: chained ternary (loading→skeleton, empty→all-clear, else→list)", 1),
      bullet("  GRNScreen: header stays; skeleton replaces ScrollView", 1),
      bullet("  TrialBalanceScreen + FinancialReportsScreen: header+tabs stay; skeleton for data body", 1),
      bullet("  Detail screens (PO, SO, Vendor, Customer, Item Ledger, Partner): SafeAreaView + DetailSkeleton", 1),
      bullet("Keyboard UX improvements on all list/search screens:"),
      bullet("  keyboardShouldPersistTaps='handled': users can tap results while keyboard is open", 1),
      bullet("  keyboardDismissMode='on-drag': keyboard dismisses when user scrolls the list", 1),
      bullet("  Applied to: Dashboard, PO, SO, Materials, Partners, Companies, JournalEntries, Inventory, TrialBalance, Alerts, GRN", 1),
      body(""),
      body("Note: This document is automatically updated by the scheduled build agent after each session.", { italics: true, color: GRAY }),
    ],
  }],
});

Packer.toBuffer(doc).then((buffer) => {
  fs.writeFileSync("FEATURES.docx", buffer);
  console.log("FEATURES.docx generated successfully");
});
